In [8]:
#Independent variables
import random
import numpy as np
import pandas as pd


In [9]:
df = pd.read_csv('iris.csv',sep = ',')
df = df.replace('Iris-setosa', 1)
df = df.replace('Iris-versicolor', 2)
df = df.replace('Iris-virginica', 3)
# df["f1"] = 10 * df["f1"]
# df["f2"] = 10 * df["f2"]
# df["f3"] = 10 * df["f3"]
# df["f4"] = 10 * df["f4"]
labels = df['labels'].to_numpy()
df = df.drop(columns=['labels'])
input_set = df.to_numpy()
print(input_set)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
#Define Hyperparameters
np.random.seed(42)
weights = np.random.rand(4,1)
bias = np.random.rand(1)
lr = 0.05 #learning rate
print(input_set.shape)
print(weights.shape)
print(bias)
print(lr)

(150, 4)
(4, 1)
[0.15601864]
0.05


In [11]:
#define activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [12]:
#define derivative
def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [13]:
#train ANN model
for epoch in range(25000):
    inputs = input_set  # set aside the original input
    XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
    z = sigmoid(XW)  #sigmoid activation function
    
#     print ("sigmoid output is:",z )
    error = z - labels  #backprop step1
    
#     print ("error is ",error)
#     print("error sum is",error.sum())   #backpro step 2
    
    dcost = error
    dpred = sigmoid_derivative(z)
    
#     print("sigmoid derivative is ",dpred)
    z_del = dcost * dpred
    inputs = input_set.T 
#     print(inputs.shape)
#     print(z_del.shape)
#     print(weights.shape)  
    weights = weights - lr*np.dot(inputs, z_del)
    for num in z_del:
        bias = bias - lr*num

In [14]:
print(weights)
print(bias)

[[1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 1.26623870e+00 1.26623870e+00
  1.26623870e+00 1.26623870e+00 2.15413331e+05 2.15413331e+05
  2.15413331e+05 2.15413331e+05 2.15413331e+05 2.15413331e+05
  2.15413331e+05 2.15413331e+05 2.15413331e+05 2.15413331e+05
  2.15413331e+05 2.15413331e+05 2.15413331e+05 2.15413331e+05
  2.1541

# Predict Points

In [1]:
single_pt = np.array([1,0,0])
print(np.dot(single_pt, weights))
result = sigmoid(np.dot(single_pt, weights) + bias)
print(result)

NameError: name 'np' is not defined

In [9]:
single_pt = np.array([0,1,0])
result = sigmoid(np.dot(single_pt, weights) + bias)
print(result)

[0.98778682]
