In [89]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from keras.models import Sequential
from keras.layers import Dense
df = pd.read_csv('diabetes.csv',sep = ',')
len(df)

768

In [90]:
df['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']*100
df.DiabetesPedigreeFunction = df.DiabetesPedigreeFunction.astype(int)
df.BMI = df.BMI.astype(int) 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   

   DiabetesPedigreeFunction  Age  Outcome  
0                        62   50        1  
1                        35   31        0  
2                        67   32        1  
3                        16   21        0  
4                       228   33        1

In [91]:
dataset = df.to_numpy()

X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]

In [92]:
print(X[:5])
print(y[:5])

[[  6 148  72  35   0  33  62  50]
 [  1  85  66  29   0  26  35  31]
 [  8 183  64   0   0  23  67  32]
 [  1  89  66  23  94  28  16  21]
 [  0 137  40  35 168  43 228  33]]
[1 0 1 0 1]


In [93]:
# define the keras model
model = Sequential()
# model.add(Dense(12, input_dim=8, activation='sigmoid'))
# model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [94]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [95]:
4
...
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
50/50 [==============================] - 1s 511us/step - loss: 59.3947 - accuracy: 0.6398
Epoch 2/150
50/50 [==============================] - 0s 492us/step - loss: 55.0585 - accuracy: 0.6167
Epoch 3/150
50/50 [==============================] - 0s 516us/step - loss: 40.9064 - accuracy: 0.6655
Epoch 4/150
50/50 [==============================] - 0s 530us/step - loss: 39.6689 - accuracy: 0.6229
Epoch 5/150
50/50 [==============================] - 0s 485us/step - loss: 30.7841 - accuracy: 0.6426
Epoch 6/150
50/50 [==============================] - 0s 510us/step - loss: 24.0154 - accuracy: 0.6065
Epoch 7/150
50/50 [==============================] - 0s 510us/step - loss: 17.2378 - accuracy: 0.6382
Epoch 8/150
50/50 [==============================] - 0s 490us/step - loss: 15.5383 - accuracy: 0.6430
Epoch 9/150
50/50 [==============================] - 0s 489us/step - loss: 13.2205 - accuracy: 0.6013
Epoch 10/150
50/50 [==============================] - 0s 490us/step - loss: 11.222

50/50 [==============================] - 0s 496us/step - loss: 0.6365 - accuracy: 0.6718
Epoch 82/150
50/50 [==============================] - 0s 551us/step - loss: 0.6630 - accuracy: 0.6434
Epoch 83/150
50/50 [==============================] - 0s 502us/step - loss: 0.6160 - accuracy: 0.6765
Epoch 84/150
50/50 [==============================] - 0s 510us/step - loss: 0.6426 - accuracy: 0.6555
Epoch 85/150
50/50 [==============================] - 0s 510us/step - loss: 0.6735 - accuracy: 0.6512
Epoch 86/150
50/50 [==============================] - 0s 510us/step - loss: 0.6202 - accuracy: 0.6905
Epoch 87/150
50/50 [==============================] - 0s 469us/step - loss: 0.6169 - accuracy: 0.6832
Epoch 88/150
50/50 [==============================] - 0s 476us/step - loss: 0.6313 - accuracy: 0.6775
Epoch 89/150
50/50 [==============================] - 0s 489us/step - loss: 0.5980 - accuracy: 0.7087
Epoch 90/150
50/50 [==============================] - 0s 507us/step - loss: 0.6258 - accuracy: 

In [96]:
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (10, 1)                   9         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None


In [97]:
4
...
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

16/16 [==============================] - 0s 533us/step - loss: 0.5906 - accuracy: 0.7080
Accuracy: 70.80


In [98]:
for layer in model.layers: 
    print(layer.get_config())
    print(layer.get_weights())
    
    w = layer.get_weights()

{'name': 'dense_7', 'trainable': True, 'dtype': 'float32', 'units': 1, 'activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
[array([[ 0.13780318],
       [ 0.01416919],
       [-0.02588373],
       [-0.00855214],
       [-0.00014193],
       [ 0.02422312],
       [ 0.00477195],
       [-0.02042699]], dtype=float32), array([-0.8291709], dtype=float32)]


In [99]:
weights = w[0]
bias = w[1]

In [100]:
predictions = model.predict(X1)
predictions

array([[0.2547701 ],
       [0.28608483],
       [0.15945238],
       [0.47402066],
       [0.22810316],
       [0.41006234],
       [0.36856842],
       [0.48883212],
       [0.4727294 ],
       [0.36441672],
       [0.44698748],
       [0.39167997],
       [0.36178818],
       [0.39742944],
       [0.40166792],
       [0.55382705],
       [0.47131506],
       [0.42024612],
       [0.6247205 ],
       [0.24996403],
       [0.18180612],
       [0.35006982],
       [0.7627344 ],
       [0.6583028 ],
       [0.54646045],
       [0.35427058],
       [0.2685075 ],
       [0.3444686 ],
       [0.34065518],
       [0.33720693],
       [0.51123685],
       [0.41194135],
       [0.31001112],
       [0.83130103],
       [0.39921618],
       [0.88502014],
       [0.13974062],
       [0.11045307],
       [0.3401447 ],
       [0.32435763],
       [0.44607708],
       [0.44393483],
       [0.35922652],
       [0.24669391],
       [0.20299786],
       [0.6262442 ],
       [0.6753552 ],
       [0.479

In [101]:

rounded= [round(x[0]) for x in predictions]
rounded

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,


In [102]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, rounded)

0.7313432835820896

In [103]:
print(rounded)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


In [104]:
print(y1[:10])

[0 0 1 0 0 0 1 0 0 0]


In [105]:
for i in range(weights.shape[0]):
    weights[i][0] = int(weights[i][0]*1000)
weights


array([[137.],
       [ 14.],
       [-25.],
       [ -8.],
       [  0.],
       [ 24.],
       [  4.],
       [-20.]], dtype=float32)

In [106]:
b = int(bias*100)

In [107]:
def sigmoidfrac(x):
    if(x<=5):
        return 1
    else:
        return 0

In [108]:
final = np.zeros((len(X1),1))
for i in range(len(X1)):
    num=0
    den=0
    a = X1[i]
    for j in range(len(a)):
        num = num + a[j]*weights[j][0] 
    x = int(num+bias)
    print(x)
    pred  = sigmoidfrac(x)
    final[i] = pred

-186
-37
-802
738
-327
505
349
800
699
305
663
447
302
413
474
1086
758
546
1364
-190
-608
274
1969
1478
1034
244
-129
248
215
148
877
469
42
2371
386
2823
-928
-1246
205
132
665
646
272
-214
-481
1413
1570
809
-57
399
94
126
-358
30
20
604
-179
315
1240
986
431
1489
-49
735
-258
621
138
183
807
39
-151
-94
694
461
364
778
1273
789
1555
293
231
771
735
743
643
202
1491
705
720
1161
1212
15
354
793
787
1069
-726
1078
844
760
-375
2233
-177
912
3145
740
1404
-177
317
204
732
1504
1198
663
1464
234
191
-308
742
2009
-196
193
1677
97
545
-316
285
401
448
274
1214
-414
627
-5
1151
1604
62
85
828
-457
-426
1045
643
2103
212
729
556
1595
966
13
92
526
596
867
78
1435
81
-11
626
24
1177
1802
507
1234
707
-235
-156
861
607
1082
1287
392
-500
632
31
2029
874
245
1216
461
-298
879
177
737
-585
549
866
396
482
50
829
1370
789
896
161
412
954
1645
529
1345
377
265
216
2291
203
97
2483
1177
1502
439
1298
350
1737
609
92
2502
1130
409
304
-125
-452
398
282
128
-687
113
138
165
739
597
216
957
1045
56

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, final)

0.5559701492537313

In [110]:
print(final)

[[1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.