In [118]:
#Independent variables
import random
import numpy as np
import pandas as pd
from numpy import loadtxt
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score


In [119]:
df = pd.read_csv('diabetes.csv',sep = ',')

In [120]:
df['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']*100
df.DiabetesPedigreeFunction = df.DiabetesPedigreeFunction.astype(int)
df.BMI = df.BMI.astype(int) 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   

   DiabetesPedigreeFunction  Age  Outcome  
0                        62   50        1  
1                        35   31        0  
2                        67   32        1  
3                        16   21        0  
4                       228   33        1

In [121]:
dataset = df.to_numpy()

In [122]:
# dataset = loadtxt('pima-diabetes.txt', delimiter=',')

# print(type(dataset))

In [123]:
X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]


In [124]:
#Define Hyperparameters
np.random.seed(42)
weights = np.random.rand(8,1)
bias = np.random.rand(1)
lr = 0.00018 #learning rate
weights

array([[0.37454012],
       [0.95071431],
       [0.73199394],
       [0.59865848],
       [0.15601864],
       [0.15599452],
       [0.05808361],
       [0.86617615]])

In [125]:
bias

array([0.60111501])

In [126]:
X[0][:]

array([  6, 148,  72,  35,   0,  33,  62,  50], dtype=int64)

In [127]:
labels = np.reshape(y, (500,1))

In [128]:
#define activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [129]:
#define derivative
def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [130]:
inputs = X  # set aside the original input
 # dot product of input and add bias
XW = np.dot(inputs, weights)+ bias 
print(XW)


[[269.26849425]
 [180.39931185]
 [259.62287896]
 [185.82260932]
 [255.82755196]
 [197.97104647]
 [174.11727682]
 [145.01266483]
 [402.99666861]
 [240.81757763]
 [206.8819621 ]
 [256.69028355]
 [257.00325265]
 [428.39069959]
 [303.11742351]
 [133.47981214]
 [275.35994294]
 [191.94427024]
 [192.89469871]
 [230.52671849]
 [280.67597829]
 [210.18143617]
 [299.65312548]
 [227.77266407]
 [303.25796062]
 [249.44336902]
 [243.39088933]
 [197.7607925 ]
 [286.08170231]
 [221.18609854]
 [237.28922777]
 [301.37127694]
 [167.16341048]
 [185.91984755]
 [242.13964488]
 [231.55750257]
 [229.45466617]
 [227.39618459]
 [194.05245552]
 [283.11621815]
 [274.98134074]
 [233.45145716]
 [228.46216521]
 [356.85101877]
 [241.77740547]
 [282.57294741]
 [213.66723621]
 [163.04683729]
 [203.52523068]
 [125.57863388]
 [201.70338397]
 [177.4788416 ]
 [182.3125273 ]
 [362.02047103]
 [318.45082161]
 [136.13566115]
 [344.2965163 ]
 [252.77280726]
 [254.11932117]
 [220.4124462 ]
 [101.14240441]
 [223.08695439]
 [128.13

In [131]:
z = sigmoid(XW)  #sigmoid activation function
print(z[:5])
error = z - labels  #backprop step1
print(error[:5])
dcost = error


[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [132]:
dpred = sigmoid_derivative(z)
print(dpred)


[[0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19

In [133]:
z_del = dcost * dpred
inputs = X.T
print(z_del)
print(inputs)


[[0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19

In [134]:
print(inputs[6][:])

[ 62  35  67  16 228  20  24  13  15  23  19  53 144  39  58  48  55  25
  18  52  70  38  45  26  25  20  25  48  24  33  54  85  26  18  51  96
  42  66  50 139  27  69  23  72  29 189  56  58  34  30  49  52  34  46
  71  24  25  96 178  17  30  27  58  69  25  20  85  84  33  18  86  41
  58  23  39  14  39  37  27  30  14  10  76  23  22  69  17  32  15  16
  25  44  26  27  76  25  13  32  35  32 122  17  26  28  93  80  20  28
  33  24  19  54  19  39  58  53  22  65  44  22  75  26  40  18  27  49
  45  26  40  74  36 111  35  45  64   8  59  53  70  15  26  28  31  27
  23  57   9 140  21   8  39  43 118  68  13  33  63  83  22  81  29  20
  16  36  74  72  25  70  47  49  18  54  77  67  37  71  38  31  19  95
   8  72  29  26  24  74  61 132  64  36  14  37  38  57  13  39  18  67
  90  15  87  23  78  23  32  40  60  15  28  35  28  37  16  43  26  74
  51  46 122  26 107  80  20  68  66  10  19  65 232   8  64  23  58  39
  29  47  58  68  83  58  19  44  40 131  32 121  2

In [135]:
print(z_del)

[[0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19

In [136]:
print(X)

[[  6 148  72 ...  33  62  50]
 [  1  85  66 ...  26  35  31]
 [  8 183  64 ...  23  67  32]
 ...
 [  2  81  72 ...  30  54  25]
 [  7 195  70 ...  25  16  55]
 [  6 154  74 ...  29  83  39]]


In [137]:
print(lr)

0.00018


In [138]:
print(lr*np.dot(inputs,z_del))

[[0.03659341]
 [1.24364519]
 [0.76750614]
 [0.22462127]
 [0.76676295]
 [0.33337519]
 [0.48951653]
 [0.35206119]]


In [139]:
weights = weights - lr*np.dot(inputs, z_del)
print(weights)
print(lr*z_del)
for num in z_del:
    bias = bias - lr*num
print(bias)

[[ 0.33794671]
 [-0.29293088]
 [-0.0355122 ]
 [ 0.37403721]
 [-0.61074431]
 [-0.17738067]
 [-0.43143291]
 [ 0.51411495]]
[[0.        ]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.        ]
 [0.        ]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.00003539]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.00003539]
 [0.        ]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.00003539]
 [0.        ]
 [0.0000353

In [140]:
weights

array([[ 0.33794671],
       [-0.29293088],
       [-0.0355122 ],
       [ 0.37403721],
       [-0.61074431],
       [-0.17738067],
       [-0.43143291],
       [ 0.51411495]])

In [141]:
bias

array([0.58986094])

In [142]:

#train ANN model
for epoch in range(10000):
    inputs = X  # set aside the original input
    XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
    z = sigmoid(XW)  #sigmoid activation function
    error = z - labels  #backprop step1
    
    dcost = error
    dpred = sigmoid_derivative(z)

    z_del = dcost * dpred
    inputs = X.T
    
    weights = weights - lr*np.dot(inputs, z_del)
    
    for num in z_del:
        bias = bias - lr*num
    print(bias)    

[0.59786875]
[0.58661469]
[0.59480462]
[0.58355055]
[0.59174055]
[0.58048648]
[0.58867648]
[0.57742242]
[0.58561242]
[0.57436046]
[0.58255046]
[0.57151776]
[0.57970776]
[0.57265116]
[0.58084116]
[0.56973751]
[0.57792751]
[0.56690981]
[0.57509981]
[0.56694989]
[0.57513989]
[0.56413682]
[0.57232682]
[0.56325693]
[0.57140193]
[0.56123392]
[0.56937892]
[0.56042485]
[0.56856985]
[0.55843885]
[0.56658385]
[0.55741553]
[0.56532609]
[0.55601844]
[0.56416344]
[0.55439275]
[0.56253774]
[0.55311848]
[0.56115399]
[0.55183323]
[0.55994283]
[0.55037141]
[0.55847774]
[0.54906799]
[0.55705057]
[0.54783841]
[0.55591426]
[0.54634569]
[0.55433868]
[0.54500863]
[0.55286397]
[0.5435876]
[0.55113833]
[0.54235976]
[0.54964358]
[0.54078679]
[0.54802808]
[0.53935987]
[0.54648879]
[0.53786255]
[0.54505383]
[0.5362103]
[0.54341583]
[0.53480217]
[0.54188544]
[0.53333891]
[0.54052389]
[0.53162269]
[0.53886085]
[0.53020362]
[0.53730598]
[0.52875822]
[0.53594204]
[0.52704974]
[0.53427239]
[0.52563388]
[0.53265057]
[

[0.09383468]
[0.08513971]
[0.09228806]
[0.08359308]
[0.09074134]
[0.08204637]
[0.08919454]
[0.08049956]
[0.08764766]
[0.07895267]
[0.08610068]
[0.0774057]
[0.08455363]
[0.07585864]
[0.08300649]
[0.0743115]
[0.08145927]
[0.07276428]
[0.07991197]
[0.07121698]
[0.07836459]
[0.0696696]
[0.07681714]
[0.06812214]
[0.0752696]
[0.06657461]
[0.073722]
[0.065027]
[0.07217431]
[0.06347932]
[0.07062656]
[0.06193157]
[0.06907874]
[0.06038374]
[0.06753084]
[0.05883585]
[0.06598288]
[0.05728789]
[0.06443485]
[0.05573986]
[0.06288676]
[0.05419177]
[0.0613386]
[0.05264361]
[0.05979037]
[0.05109539]
[0.05824209]
[0.04954711]
[0.05669375]
[0.04799877]
[0.05514534]
[0.04645037]
[0.05359688]
[0.04490191]
[0.05204837]
[0.0433534]
[0.0504998]
[0.04180483]
[0.04895117]
[0.04025621]
[0.0474025]
[0.03870754]
[0.04585377]
[0.03715882]
[0.04430499]
[0.03561005]
[0.04275617]
[0.03406123]
[0.0412073]
[0.03251237]
[0.03965838]
[0.03096346]
[0.03810942]
[0.0294145]
[0.03656042]
[0.02786551]
[0.03501138]
[0.02631647]


[-0.41429719]
[-0.40716013]
[-0.41583767]
[-0.40870067]
[-0.41737811]
[-0.41024118]
[-0.41891852]
[-0.41178165]
[-0.4204589]
[-0.41332208]
[-0.42199924]
[-0.41486249]
[-0.42353955]
[-0.41640285]
[-0.42507982]
[-0.41794319]
[-0.42662006]
[-0.41948349]
[-0.42816026]
[-0.42102375]
[-0.42970043]
[-0.42256398]
[-0.43124056]
[-0.42410417]
[-0.43278066]
[-0.42564433]
[-0.43432072]
[-0.42718445]
[-0.43586074]
[-0.42872454]
[-0.43740074]
[-0.43026459]
[-0.43894069]
[-0.4318046]
[-0.4404806]
[-0.43334457]
[-0.44202049]
[-0.43488452]
[-0.44356033]
[-0.43642443]
[-0.44510013]
[-0.43796427]
[-0.44663993]
[-0.43950414]
[-0.4481796]
[-0.4410439]
[-0.44971933]
[-0.44258362]
[-0.45125908]
[-0.44412348]
[-0.45279844]
[-0.44566294]
[-0.45433832]
[-0.44720266]
[-0.45587788]
[-0.44874264]
[-0.45741662]
[-0.45028122]
[-0.45895761]
[-0.45182183]
[-0.46049582]
[-0.45336155]
[-0.46203386]
[-0.45489775]
[-0.46357909]
[-0.45644322]
[-0.46510975]
[-0.45797863]
[-0.46665115]
[-0.45951085]
[-0.46820661]
[-0.4610724

[-0.87355319]
[-0.86640592]
[-0.87512058]
[-0.86797566]
[-0.87665896]
[-0.86951447]
[-0.87823902]
[-0.87110191]
[-0.87974217]
[-0.87266267]
[-0.88121958]
[-0.8740747]
[-0.88294924]
[-0.87580431]
[-0.88428925]
[-0.87721401]
[-0.8859283]
[-0.87878324]
[-0.88746764]
[-0.88032274]
[-0.88904746]
[-0.88190324]
[-0.89057115]
[-0.88346687]
[-0.89206754]
[-0.88492496]
[-0.8937447]
[-0.88660097]
[-0.89514624]
[-0.88808967]
[-0.89668484]
[-0.88953984]
[-0.89836539]
[-0.89122045]
[-0.89976858]
[-0.89263144]
[-0.90148689]
[-0.89434227]
[-0.90285288]
[-0.89579633]
[-0.90442524]
[-0.89727988]
[-0.90606754]
[-0.89892261]
[-0.9075182]
[-0.90037657]
[-0.90919492]
[-0.90205141]
[-0.91060353]
[-0.90354684]
[-0.91213566]
[-0.9049906]
[-0.91381863]
[-0.90667369]
[-0.91522506]
[-0.90808838]
[-0.91693393]
[-0.90978942]
[-0.91831694]
[-0.91126]
[-0.9198726]
[-0.91272705]
[-0.92152991]
[-0.91438498]
[-0.92296771]
[-0.91582765]
[-0.92465033]
[-0.91750666]
[-0.92605987]
[-0.91900309]
[-0.92759144]
[-0.92044618]
[

[-1.3755167]
[-1.36845926]
[-1.37704641]
[-1.36985648]
[-1.37877653]
[-1.37172139]
[-1.38007927]
[-1.37292568]
[-1.38185964]
[-1.37475147]
[-1.38320725]
[-1.376132]
[-1.38478143]
[-1.37759151]
[-1.3864699]
[-1.37941494]
[-1.38780418]
[-1.38066551]
[-1.38953236]
[-1.38239091]
[-1.3909431]
[-1.38388751]
[-1.39246989]
[-1.38527996]
[-1.39419657]
[-1.38714157]
[-1.3955046]
[-1.38836378]
[-1.39725479]
[-1.39011517]
[-1.39865067]
[-1.3915952]
[-1.40018181]
[-1.39299189]
[-1.40190373]
[-1.39484874]
[-1.40321661]
[-1.39607495]
[-1.40496285]
[-1.3978279]
[-1.406359]
[-1.39930307]
[-1.40789218]
[-1.40070226]
[-1.40960981]
[-1.40255479]
[-1.4109273]
[-1.40376965]
[-1.41269671]
[-1.40562835]
[-1.41401696]
[-1.40682933]
[-1.41581605]
[-1.40876112]
[-1.41708872]
[-1.4100213]
[-1.41872904]
[-1.41153911]
[-1.42035337]
[-1.41329832]
[-1.42174127]
[-1.41455324]
[-1.42350918]
[-1.41645425]
[-1.42479766]
[-1.41773209]
[-1.4264262]
[-1.41923627]
[-1.42806159]
[-1.42100651]
[-1.4294417]
[-1.42225372]
[-1.43

[-1.83090767]
[-1.82377658]
[-1.83254697]
[-1.82555082]
[-1.83394213]
[-1.82685685]
[-1.83556118]
[-1.82855736]
[-1.83697483]
[-1.82984493]
[-1.83861345]
[-1.83161809]
[-1.84000913]
[-1.83292414]
[-1.84162786]
[-1.83462478]
[-1.84304064]
[-1.83591191]
[-1.84467847]
[-1.83768391]
[-1.84607469]
[-1.83898993]
[-1.84769308]
[-1.84069072]
[-1.84910513]
[-1.84197756]
[-1.85074206]
[-1.84374833]
[-1.85213885]
[-1.84505427]
[-1.85375688]
[-1.84675521]
[-1.85516833]
[-1.84804193]
[-1.85680425]
[-1.84981137]
[-1.85820165]
[-1.85111718]
[-1.8598193]
[-1.8528183]
[-1.86123028]
[-1.85410506]
[-1.8628651]
[-1.85587308]
[-1.86426313]
[-1.85717871]
[-1.86588037]
[-1.85888005]
[-1.86729101]
[-1.86016699]
[-1.86892463]
[-1.8619335]
[-1.87032334]
[-1.86323889]
[-1.87194015]
[-1.86494051]
[-1.87335056]
[-1.86622776]
[-1.87498289]
[-1.86799265]
[-1.87638231]
[-1.86929776]
[-1.87799868]
[-1.87099973]
[-1.87940896]
[-1.87228742]
[-1.88103991]
[-1.8740506]
[-1.8824401]
[-1.87535534]
[-1.88405599]
[-1.87705778

[-2.27039294]
[-2.27909351]
[-2.27215719]
[-2.28051319]
[-2.27339585]
[-2.28209633]
[-2.27516052]
[-2.28351592]
[-2.27639851]
[-2.28509892]
[-2.27816364]
[-2.28651841]
[-2.27940093]
[-2.28810127]
[-2.28116653]
[-2.28952064]
[-2.28240309]
[-2.29110338]
[-2.28416918]
[-2.29252261]
[-2.28540499]
[-2.29410523]
[-2.2871716]
[-2.29552432]
[-2.28840663]
[-2.29710682]
[-2.29017376]
[-2.29852576]
[-2.291408]
[-2.30010815]
[-2.29317567]
[-2.30152693]
[-2.2944091]
[-2.30310922]
[-2.29617732]
[-2.30452783]
[-2.29740993]
[-2.30611001]
[-2.2991787]
[-2.30752845]
[-2.30041047]
[-2.30911052]
[-2.30217981]
[-2.31052878]
[-2.30341074]
[-2.31211076]
[-2.30518063]
[-2.31352884]
[-2.30641072]
[-2.31511071]
[-2.30818118]
[-2.31652861]
[-2.30941042]
[-2.31811037]
[-2.31118143]
[-2.31952809]
[-2.31240984]
[-2.32110974]
[-2.31418139]
[-2.32252729]
[-2.31540897]
[-2.32410883]
[-2.31718108]
[-2.32552616]
[-2.31840778]
[-2.3271076]
[-2.32018035]
[-2.32852493]
[-2.32140648]
[-2.33010617]
[-2.32317983]
[-2.33152258

[-2.71874961]
[-2.72719121]
[-2.72022922]
[-2.72867073]
[-2.72170881]
[-2.73015023]
[-2.72318838]
[-2.73162971]
[-2.72466794]
[-2.73310917]
[-2.72614747]
[-2.73458862]
[-2.72762699]
[-2.73606805]
[-2.72910649]
[-2.73754746]
[-2.73058598]
[-2.73902686]
[-2.73206544]
[-2.74050623]
[-2.73354489]
[-2.7419856]
[-2.73502433]
[-2.74346494]
[-2.73650374]
[-2.74494427]
[-2.73798314]
[-2.74642359]
[-2.73946253]
[-2.74790289]
[-2.74094189]
[-2.74938217]
[-2.74242124]
[-2.75086144]
[-2.74390058]
[-2.75234069]
[-2.7453799]
[-2.75381993]
[-2.7468592]
[-2.75529915]
[-2.74833849]
[-2.75677836]
[-2.74981776]
[-2.75825755]
[-2.75129702]
[-2.75973673]
[-2.75277627]
[-2.76121589]
[-2.75425549]
[-2.76269504]
[-2.75573471]
[-2.76417417]
[-2.75721391]
[-2.76565329]
[-2.75869309]
[-2.7671324]
[-2.76017226]
[-2.76861149]
[-2.76165142]
[-2.77009057]
[-2.76313056]
[-2.77156964]
[-2.76460969]
[-2.77304869]
[-2.7660888]
[-2.77452773]
[-2.7675679]
[-2.77600675]
[-2.76904699]
[-2.77748576]
[-2.77052606]
[-2.77896476

[-3.16505082]
[-3.17347218]
[-3.16652726]
[-3.17494853]
[-3.16800369]
[-3.17642487]
[-3.16948011]
[-3.1779012]
[-3.17095653]
[-3.17937753]
[-3.17243295]
[-3.18085385]
[-3.17390936]
[-3.18233017]
[-3.17538576]
[-3.18380648]
[-3.17686217]
[-3.18528279]
[-3.17833856]
[-3.18675909]
[-3.17981496]
[-3.18823539]
[-3.18129134]
[-3.18971168]
[-3.18276773]
[-3.19118797]
[-3.18424411]
[-3.19266425]
[-3.18572048]
[-3.19414053]
[-3.18719685]
[-3.19561681]
[-3.18867322]
[-3.19709308]
[-3.19014958]
[-3.19856934]
[-3.19162594]
[-3.2000456]
[-3.1931023]
[-3.20152186]
[-3.19457865]
[-3.20299811]
[-3.19605499]
[-3.20447436]
[-3.19753134]
[-3.20595061]
[-3.19900768]
[-3.20742685]
[-3.20048401]
[-3.20890308]
[-3.20196035]
[-3.21037931]
[-3.20343667]
[-3.21185554]
[-3.204913]
[-3.21333177]
[-3.20638932]
[-3.21480799]
[-3.20786564]
[-3.2162842]
[-3.20934195]
[-3.21776042]
[-3.21081827]
[-3.21923663]
[-3.21229457]
[-3.22071283]
[-3.21377088]
[-3.22218903]
[-3.21524718]
[-3.22366523]
[-3.21672348]
[-3.22514143

[-3.6372058]
[-3.63031576]
[-3.63868556]
[-3.63179566]
[-3.64016536]
[-3.6332756]
[-3.6416452]
[-3.63475557]
[-3.64312506]
[-3.63623557]
[-3.64460497]
[-3.6377156]
[-3.6460849]
[-3.63919567]
[-3.64756487]
[-3.64067578]
[-3.64904488]
[-3.64215591]
[-3.65052492]
[-3.64363608]
[-3.65200499]
[-3.64511628]
[-3.6534851]
[-3.64659652]
[-3.65496525]
[-3.64807679]
[-3.65644542]
[-3.64955709]
[-3.65792564]
[-3.65103742]
[-3.65940588]
[-3.65251779]
[-3.66088617]
[-3.6539982]
[-3.66236648]
[-3.65547863]
[-3.66384683]
[-3.6569591]
[-3.66532722]
[-3.65843961]
[-3.66680764]
[-3.65992014]
[-3.66828809]
[-3.66140071]
[-3.66976858]
[-3.66288132]
[-3.6712491]
[-3.66436195]
[-3.67272966]
[-3.66584262]
[-3.67421025]
[-3.66732333]
[-3.67569088]
[-3.66880407]
[-3.67717154]
[-3.67028484]
[-3.67865223]
[-3.67176564]
[-3.68013296]
[-3.67324648]
[-3.68161372]
[-3.67472735]
[-3.68309452]
[-3.67620825]
[-3.68457535]
[-3.67768919]
[-3.68605622]
[-3.67917016]
[-3.68753712]
[-3.68065117]
[-3.68901805]
[-3.6821322]
[-

[-4.07476887]
[-4.06789807]
[-4.07625335]
[-4.06938259]
[-4.07773783]
[-4.07086711]
[-4.07922231]
[-4.07235163]
[-4.08070678]
[-4.07383614]
[-4.08219125]
[-4.07532065]
[-4.08367572]
[-4.07680516]
[-4.08516019]
[-4.07828966]
[-4.08664465]
[-4.07977416]
[-4.08812911]
[-4.08125866]
[-4.08961356]
[-4.08274315]
[-4.09109801]
[-4.08422764]
[-4.09258246]
[-4.08571213]
[-4.09406691]
[-4.08719661]
[-4.09555135]
[-4.08868109]
[-4.09703579]
[-4.09016557]
[-4.09852023]
[-4.09165004]
[-4.10000466]
[-4.09313451]
[-4.10148909]
[-4.09461898]
[-4.10297351]
[-4.09610344]
[-4.10445793]
[-4.09758789]
[-4.10594235]
[-4.09907235]
[-4.10742677]
[-4.1005568]
[-4.10891118]
[-4.10204125]
[-4.11039559]
[-4.10352569]
[-4.11187999]
[-4.10501013]
[-4.11336439]
[-4.10649456]
[-4.11484879]
[-4.107979]
[-4.11633318]
[-4.10946342]
[-4.11781757]
[-4.11094785]
[-4.11930196]
[-4.11243227]
[-4.12078634]
[-4.11391668]
[-4.12227072]
[-4.1154011]
[-4.1237551]
[-4.1168855]
[-4.12523947]
[-4.11836991]
[-4.12672383]
[-4.11985431

[-4.54066052]
[-4.53379626]
[-4.5421432]
[-4.53527897]
[-4.54362587]
[-4.53676166]
[-4.54510853]
[-4.53824435]
[-4.54659118]
[-4.53972702]
[-4.54807382]
[-4.54120968]
[-4.54955644]
[-4.54269233]
[-4.55103905]
[-4.54417498]
[-4.55252166]
[-4.5456576]
[-4.55400425]
[-4.54714022]
[-4.55548682]
[-4.54862283]
[-4.55696939]
[-4.55010542]
[-4.55845195]
[-4.55158801]
[-4.55993449]
[-4.55307058]
[-4.56141702]
[-4.55455314]
[-4.56289954]
[-4.55603569]
[-4.56438205]
[-4.55751822]
[-4.56586454]
[-4.55900075]
[-4.56734702]
[-4.56048326]
[-4.56882949]
[-4.56196576]
[-4.57031195]
[-4.56344824]
[-4.57179439]
[-4.56493072]
[-4.57327682]
[-4.56641318]
[-4.57475924]
[-4.56789563]
[-4.57624164]
[-4.56937807]
[-4.57772403]
[-4.57086049]
[-4.57920641]
[-4.5723429]
[-4.58068877]
[-4.5738253]
[-4.58217113]
[-4.57530768]
[-4.58365346]
[-4.57679005]
[-4.58513579]
[-4.57827241]
[-4.5866181]
[-4.57975475]
[-4.58810039]
[-4.58123708]
[-4.58958267]
[-4.58271939]
[-4.59106494]
[-4.5842017]
[-4.59254719]
[-4.58568398

[-4.97649143]
[-4.98482061]
[-4.97797008]
[-4.9862992]
[-4.97944872]
[-4.98777778]
[-4.98092734]
[-4.98925634]
[-4.98240596]
[-4.9907349]
[-4.98388457]
[-4.99221345]
[-4.98536316]
[-4.99369199]
[-4.98684175]
[-4.99517052]
[-4.98832032]
[-4.99664903]
[-4.98979889]
[-4.99812754]
[-4.99127744]
[-4.99960604]
[-4.99275599]
[-5.00108452]
[-4.99423452]
[-5.002563]
[-4.99571305]
[-5.00404146]
[-4.99719156]
[-5.00551992]
[-4.99867006]
[-5.00699836]
[-5.00014856]
[-5.0084768]
[-5.00162704]
[-5.00995522]
[-5.00310551]
[-5.01143364]
[-5.00458397]
[-5.01291204]
[-5.00606243]
[-5.01439044]
[-5.00754087]
[-5.01586882]
[-5.0090193]
[-5.01734719]
[-5.01049772]
[-5.01882556]
[-5.01197613]
[-5.02030391]
[-5.01345454]
[-5.02178225]
[-5.01493293]
[-5.02326059]
[-5.01641131]
[-5.02473891]
[-5.01788968]
[-5.02621722]
[-5.01936804]
[-5.02769553]
[-5.02084639]
[-5.02917382]
[-5.02232473]
[-5.0306521]
[-5.02380306]
[-5.03213038]
[-5.02528138]
[-5.03360864]
[-5.02675969]
[-5.03508689]
[-5.02823799]
[-5.03656514]

[-5.4737106]
[-5.46687494]
[-5.47518605]
[-5.46835042]
[-5.47666148]
[-5.4698259]
[-5.4781369]
[-5.47130136]
[-5.47961232]
[-5.47277681]
[-5.48108772]
[-5.47425226]
[-5.48256311]
[-5.47572769]
[-5.4840385]
[-5.47720312]
[-5.48551387]
[-5.47867853]
[-5.48698924]
[-5.48015394]
[-5.48846459]
[-5.48162933]
[-5.48993994]
[-5.48310472]
[-5.49141527]
[-5.48458009]
[-5.4928906]
[-5.48605546]
[-5.49436591]
[-5.48753082]
[-5.49584122]
[-5.48900616]
[-5.49731651]
[-5.4904815]
[-5.4987918]
[-5.49195682]
[-5.50026707]
[-5.49343214]
[-5.50174234]
[-5.49490745]
[-5.5032176]
[-5.49638274]
[-5.50469284]
[-5.49785803]
[-5.50616808]
[-5.49933331]
[-5.50764331]
[-5.50080857]
[-5.50911852]
[-5.50228383]
[-5.51059373]
[-5.50375908]
[-5.51206893]
[-5.50523431]
[-5.51354411]
[-5.50670954]
[-5.51501929]
[-5.50818476]
[-5.51649446]
[-5.50965996]
[-5.51796961]
[-5.51113516]
[-5.51944476]
[-5.51261035]
[-5.5209199]
[-5.51408552]
[-5.52239502]
[-5.51556069]
[-5.52387014]
[-5.51703585]
[-5.52534525]
[-5.51851099]
[

[-5.92029386]
[-5.91346916]
[-5.92176606]
[-5.91494139]
[-5.92323825]
[-5.91641361]
[-5.92471043]
[-5.91788582]
[-5.92618259]
[-5.91935802]
[-5.92765474]
[-5.92083021]
[-5.92912689]
[-5.92230238]
[-5.93059902]
[-5.92377455]
[-5.93207114]
[-5.9252467]
[-5.93354325]
[-5.92671884]
[-5.93501534]
[-5.92819097]
[-5.93648743]
[-5.92966309]
[-5.9379595]
[-5.93113519]
[-5.93943156]
[-5.93260729]
[-5.94090361]
[-5.93407937]
[-5.94237565]
[-5.93555144]
[-5.94384768]
[-5.9370235]
[-5.9453197]
[-5.93849555]
[-5.9467917]
[-5.93996759]
[-5.94826369]
[-5.94143962]
[-5.94973567]
[-5.94291163]
[-5.95120764]
[-5.94438363]
[-5.9526796]
[-5.94585563]
[-5.95415155]
[-5.94732761]
[-5.95562349]
[-5.94879957]
[-5.95709541]
[-5.95027153]
[-5.95856732]
[-5.95174348]
[-5.96003922]
[-5.95321541]
[-5.96151111]
[-5.95468733]
[-5.96298299]
[-5.95615924]
[-5.96445486]
[-5.95763114]
[-5.96592671]
[-5.95910303]
[-5.96739856]
[-5.96057491]
[-5.96887039]
[-5.96204677]
[-5.97034221]
[-5.96351862]
[-5.97181402]
[-5.96499047

[-6.36049995]
[-6.36878389]
[-6.3619687]
[-6.37025261]
[-6.36343744]
[-6.3717213]
[-6.36490617]
[-6.37318999]
[-6.36637489]
[-6.37465867]
[-6.36784359]
[-6.37612733]
[-6.36931228]
[-6.37759599]
[-6.37078097]
[-6.37906463]
[-6.37224963]
[-6.38053326]
[-6.37371829]
[-6.38200187]
[-6.37518694]
[-6.38347048]
[-6.37665557]
[-6.38493907]
[-6.3781242]
[-6.38640766]
[-6.37959281]
[-6.38787623]
[-6.38106141]
[-6.38934479]
[-6.38252999]
[-6.39081333]
[-6.38399857]
[-6.39228187]
[-6.38546713]
[-6.39375039]
[-6.38693569]
[-6.39521891]
[-6.38840423]
[-6.39668741]
[-6.38987276]
[-6.3981559]
[-6.39134127]
[-6.39962437]
[-6.39280978]
[-6.40109284]
[-6.39427827]
[-6.40256129]
[-6.39574675]
[-6.40402973]
[-6.39721522]
[-6.40549816]
[-6.39868368]
[-6.40696658]
[-6.40015213]
[-6.40843499]
[-6.40162056]
[-6.40990338]
[-6.40308898]
[-6.41137176]
[-6.40455739]
[-6.41284013]
[-6.40602579]
[-6.41430849]
[-6.40749418]
[-6.41577684]
[-6.40896255]
[-6.41724517]
[-6.41043092]
[-6.4187135]
[-6.41189927]
[-6.4201818

[-6.84545093]
[-6.83864419]
[-6.84691541]
[-6.84010869]
[-6.84837987]
[-6.84157318]
[-6.84984432]
[-6.84303765]
[-6.85130876]
[-6.84450211]
[-6.85277318]
[-6.84596656]
[-6.85423759]
[-6.84743099]
[-6.85570199]
[-6.84889541]
[-6.85716637]
[-6.85035982]
[-6.85863074]
[-6.85182421]
[-6.8600951]
[-6.85328859]
[-6.86155944]
[-6.85475295]
[-6.86302377]
[-6.8562173]
[-6.86448808]
[-6.85768164]
[-6.86595238]
[-6.85914596]
[-6.86741667]
[-6.86061027]
[-6.86888094]
[-6.86207457]
[-6.8703452]
[-6.86353885]
[-6.87180944]
[-6.86500312]
[-6.87327368]
[-6.86646737]
[-6.87473789]
[-6.86793161]
[-6.8762021]
[-6.86939584]
[-6.87766629]
[-6.87086005]
[-6.87913047]
[-6.87232425]
[-6.88059463]
[-6.87378844]
[-6.88205878]
[-6.87525261]
[-6.88352292]
[-6.87671677]
[-6.88498704]
[-6.87818092]
[-6.88645115]
[-6.87964505]
[-6.88791524]
[-6.88110917]
[-6.88937933]
[-6.88257327]
[-6.8908434]
[-6.88403736]
[-6.89230745]
[-6.88550144]
[-6.89377149]
[-6.8869655]
[-6.89523552]
[-6.88842955]
[-6.89669953]
[-6.88989359

In [143]:
print(X1[0])

[  2 117  90  19  71  25  31  21]


In [144]:
print(weights)
print(bias)

[[16.86065452]
 [ 0.76371014]
 [-2.55850531]
 [-0.97275301]
 [ 0.15593357]
 [-0.50288188]
 [ 0.30220941]
 [-2.8812979 ]]
[-6.90987505]


In [145]:
print(np.dot(X1, weights) + bias)

[[-185.22179222]
 [-198.94226424]
 [-235.59371151]
 [-105.50798202]
 [-247.42024846]
 [-109.04948212]
 [-220.54576708]
 [ -93.87733232]
 [ -94.06615639]
 [-164.82957231]
 [ -93.15729943]
 [-108.69871517]
 [-132.78497764]
 [-123.56974768]
 [-101.14196985]
 [-100.4832945 ]
 [-121.44416477]
 [-169.93952261]
 [ -11.97537881]
 [-158.37222836]
 [-200.35285366]
 [-160.58032902]
 [ 111.8430317 ]
 [ -62.08981561]
 [ -89.4647988 ]
 [-118.67556332]
 [-146.2044879 ]
 [-134.48918269]
 [-150.92372008]
 [-169.88447357]
 [ -91.02210337]
 [-190.86988788]
 [-210.35371291]
 [  74.95833568]
 [-142.94022259]
 [  88.04669156]
 [-298.36708717]
 [-298.43490716]
 [-178.04176992]
 [-197.98016275]
 [-113.92980211]
 [-115.04479787]
 [-171.83995923]
 [-206.33382176]
 [-227.53534852]
 [ -70.21454359]
 [-111.43043218]
 [-100.37852278]
 [-255.86101824]
 [-206.85544289]
 [-175.83217865]
 [-148.59968294]
 [-240.32190534]
 [-166.11568339]
 [-178.65911358]
 [ -86.20045791]
 [-233.17687967]
 [-156.20519942]
 [ -96.1895775

# Predict Points

In [146]:
pred = sigmoid(np.dot(X1, weights) + bias)
print(pred[20])
pred = np.around(pred)

[0.]


In [147]:
pred[20]

array([0.])

In [148]:
accuracy_score(y1, pred)*100

67.91044776119402

In [149]:
print(weights.shape)

(8, 1)


In [150]:
for i in range(weights.shape[0]):
    weights[i][0] = int(weights[i][0]*100)
weights


array([[1686.],
       [  76.],
       [-255.],
       [ -97.],
       [  15.],
       [ -50.],
       [  30.],
       [-288.]])

In [151]:
b = int(bias*100)

In [152]:
def sigmoidfrac(x):
    if(x>=0):
        return 1
    else:
        return 0

In [153]:
final = np.zeros((len(X1),1))
for i in range(len(X1)):
    num=0
    den=0
    a = X1[i]
    for j in range(len(a)):
        num = num + a[j]*weights[j][0] 
    x = int(num+bias)
    print(x)
    pred  = sigmoidfrac(x//100)
    final[i] = pred

-17838
-19162
-22805
-9888
-24005
-10170
-21398
-8799
-8759
-15770
-8585
-10299
-12560
-11654
-9459
-9415
-11529
-16272
-480
-15315
-19340
-15413
11825
-5512
-8250
-11160
-13959
-12794
-14497
-16293
-8474
-18376
-20355
8147
-13630
9445
-29104
-29130
-17217
-19168
-10797
-10911
-16453
-19919
-22067
-6448
-10582
-9427
-24912
-19971
-16868
-14204
-23304
-15924
-17216
-8032
-22588
-14902
-8888
-4550
-16612
-9396
-18753
-7745
-21066
-8638
-18514
-14530
-12057
-18679
-18892
-17602
-10145
-11801
-12796
-12220
-1742
-14144
-1376
-26961
-22980
-7951
-10523
-11724
-4138
-12805
-5628
-7724
-16957
-1688
-10824
-19114
-18488
-7601
-9069
-11107
-29222
-4892
-16546
-7110
-21457
8761
-20948
-12849
9507
-13568
-8719
-15658
-18083
-11659
-7871
-5936
-8215
-11504
-4754
-13678
-15068
-15186
-11518
945
-20970
-15156
-10532
-18784
-11844
-21733
-14494
-16342
-16488
-11655
-4812
-22596
-10402
-15762
-1662
341
-17316
-15880
-10557
-18658
-21414
-9096
-14458
5079
-13046
-10567
-13321
-7095
-6705
-17133
-13283


In [154]:
np.set_printoptions(suppress=True)
print(final)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [155]:
print(y1)

[0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 1 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0
 1 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 1
 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0
 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0
 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 0 1 0
 1 0 1 0 0 0 0 1 0]


In [156]:

from sklearn.metrics import accuracy_score
accuracy_score(y1, final)

0.6791044776119403