In [30]:
#Independent variables
import random
import numpy as np
import pandas as pd
from numpy import loadtxt
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score


In [31]:
df = pd.read_csv('diabetes.csv',sep = ',')

In [32]:
df['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']*100
df.DiabetesPedigreeFunction = df.DiabetesPedigreeFunction.astype(int)
df.BMI = df.BMI.astype(int) 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   

   DiabetesPedigreeFunction  Age  Outcome  
0                        62   50        1  
1                        35   31        0  
2                        67   32        1  
3                        16   21        0  
4                       228   33        1

In [33]:
dataset = df.to_numpy()

In [34]:
# dataset = loadtxt('pima-diabetes.txt', delimiter=',')

# print(type(dataset))

In [35]:
X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]


In [36]:
#Define Hyperparameters
np.random.seed(42)
weights = np.random.rand(8,1)
bias = np.random.rand(1)
lr = 0.0001 #learning rate
weights

array([[0.37454012],
       [0.95071431],
       [0.73199394],
       [0.59865848],
       [0.15601864],
       [0.15599452],
       [0.05808361],
       [0.86617615]])

In [37]:
bias

array([0.60111501])

In [38]:
X[0][:]

array([  6, 148,  72,  35,   0,  33,  62,  50], dtype=int64)

In [39]:
labels = np.reshape(y, (500,1))

In [40]:
#define activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [41]:
#define derivative
def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [42]:
inputs = X  # set aside the original input
 # dot product of input and add bias
XW = np.dot(inputs, weights)+ bias 
print(XW)


[[269.26849425]
 [180.39931185]
 [259.62287896]
 [185.82260932]
 [255.82755196]
 [197.97104647]
 [174.11727682]
 [145.01266483]
 [402.99666861]
 [240.81757763]
 [206.8819621 ]
 [256.69028355]
 [257.00325265]
 [428.39069959]
 [303.11742351]
 [133.47981214]
 [275.35994294]
 [191.94427024]
 [192.89469871]
 [230.52671849]
 [280.67597829]
 [210.18143617]
 [299.65312548]
 [227.77266407]
 [303.25796062]
 [249.44336902]
 [243.39088933]
 [197.7607925 ]
 [286.08170231]
 [221.18609854]
 [237.28922777]
 [301.37127694]
 [167.16341048]
 [185.91984755]
 [242.13964488]
 [231.55750257]
 [229.45466617]
 [227.39618459]
 [194.05245552]
 [283.11621815]
 [274.98134074]
 [233.45145716]
 [228.46216521]
 [356.85101877]
 [241.77740547]
 [282.57294741]
 [213.66723621]
 [163.04683729]
 [203.52523068]
 [125.57863388]
 [201.70338397]
 [177.4788416 ]
 [182.3125273 ]
 [362.02047103]
 [318.45082161]
 [136.13566115]
 [344.2965163 ]
 [252.77280726]
 [254.11932117]
 [220.4124462 ]
 [101.14240441]
 [223.08695439]
 [128.13

In [43]:
z = sigmoid(XW)  #sigmoid activation function
print(z[:5])
error = z - labels  #backprop step1
print(error[:5])
dcost = error


[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [44]:
dpred = sigmoid_derivative(z)
print(dpred)


[[0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19

In [45]:
z_del = dcost * dpred
inputs = X.T
print(z_del)
print(inputs)


[[0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19

In [46]:
print(inputs[6][:])

[ 62  35  67  16 228  20  24  13  15  23  19  53 144  39  58  48  55  25
  18  52  70  38  45  26  25  20  25  48  24  33  54  85  26  18  51  96
  42  66  50 139  27  69  23  72  29 189  56  58  34  30  49  52  34  46
  71  24  25  96 178  17  30  27  58  69  25  20  85  84  33  18  86  41
  58  23  39  14  39  37  27  30  14  10  76  23  22  69  17  32  15  16
  25  44  26  27  76  25  13  32  35  32 122  17  26  28  93  80  20  28
  33  24  19  54  19  39  58  53  22  65  44  22  75  26  40  18  27  49
  45  26  40  74  36 111  35  45  64   8  59  53  70  15  26  28  31  27
  23  57   9 140  21   8  39  43 118  68  13  33  63  83  22  81  29  20
  16  36  74  72  25  70  47  49  18  54  77  67  37  71  38  31  19  95
   8  72  29  26  24  74  61 132  64  36  14  37  38  57  13  39  18  67
  90  15  87  23  78  23  32  40  60  15  28  35  28  37  16  43  26  74
  51  46 122  26 107  80  20  68  66  10  19  65 232   8  64  23  58  39
  29  47  58  68  83  58  19  44  40 131  32 121  2

In [47]:
print(z_del)

[[0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19

In [48]:
print(X)

[[  6 148  72 ...  33  62  50]
 [  1  85  66 ...  26  35  31]
 [  8 183  64 ...  23  67  32]
 ...
 [  2  81  72 ...  30  54  25]
 [  7 195  70 ...  25  16  55]
 [  6 154  74 ...  29  83  39]]


In [49]:
print(lr)

0.0001


In [50]:
print(lr*np.dot(inputs,z_del))

[[0.02032967]
 [0.69091399]
 [0.4263923 ]
 [0.12478959]
 [0.42597941]
 [0.18520844]
 [0.27195363]
 [0.19558955]]


In [51]:
weights = weights - lr*np.dot(inputs, z_del)
print(weights)
print(lr*z_del)
for num in z_del:
    bias = bias - lr*num
print(bias)

[[ 0.35421044]
 [ 0.25980031]
 [ 0.30560164]
 [ 0.47386889]
 [-0.26996077]
 [-0.02921392]
 [-0.21387001]
 [ 0.67058659]]
[[0.00000000e+00]
 [1.96611933e-05]
 [0.00000000e+00]
 [1.96611933e-05]
 [0.00000000e+00]
 [1.96611933e-05]
 [0.00000000e+00]
 [1.96611933e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.96611933e-05]
 [0.00000000e+00]
 [1.96611933e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.96611933e-05]
 [0.00000000e+00]
 [1.96611933e-05]
 [1.96611933e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.96611933e-05]
 [1.96611933e-05]
 [1.96611933e-05]
 [1.96611933e-05]
 [0.00000000e+00]
 [1.96611933e-05]
 [1.96611933e-05]
 [1.96611933e-05]
 [1.96611933e-05]
 [1.96611933e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.96611933e-05]
 [1.96611933e-05]
 [1.96611933e-05]
 [0.00000000e+00]
 [1.96611933e-05]
 [0.00000000e+00]
 [1.96611933e-05]
 [1.96611933e-05]
 [0.00000000e+0

In [52]:
weights

array([[ 0.35421044],
       [ 0.25980031],
       [ 0.30560164],
       [ 0.47386889],
       [-0.26996077],
       [-0.02921392],
       [-0.21387001],
       [ 0.67058659]])

In [53]:
bias

array([0.59486275])

In [54]:

#train ANN model
for epoch in range(10000):
    inputs = X  # set aside the original input
    XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
    z = sigmoid(XW)  #sigmoid activation function
    error = z - labels  #backprop step1
    
    dcost = error
    dpred = sigmoid_derivative(z)

    z_del = dcost * dpred
    inputs = X.T
    
    weights = weights - lr*np.dot(inputs, z_del)
    
    for num in z_del:
        bias = bias - lr*num
    print(bias)    

[0.58915366]
[0.59364619]
[0.58739393]
[0.59194317]
[0.58569091]
[0.59024091]
[0.58398865]
[0.58853865]
[0.58241024]
[0.58696024]
[0.58167046]
[0.58622046]
[0.58022266]
[0.58477266]
[0.58001567]
[0.58456567]
[0.57841554]
[0.58296554]
[0.57782014]
[0.58237014]
[0.57659604]
[0.58114604]
[0.57622326]
[0.58077326]
[0.5748533]
[0.5794033]
[0.57460416]
[0.57915416]
[0.57323961]
[0.57778961]
[0.57279707]
[0.57732207]
[0.57166964]
[0.57619464]
[0.57113231]
[0.57565197]
[0.57012673]
[0.574584]
[0.56963501]
[0.57410189]
[0.56862621]
[0.57315105]
[0.56791306]
[0.57236855]
[0.56718898]
[0.57169212]
[0.56634004]
[0.57077854]
[0.56567752]
[0.57006185]
[0.56480482]
[0.5691646]
[0.56406111]
[0.56831101]
[0.56329938]
[0.56750896]
[0.56241445]
[0.56657431]
[0.56166005]
[0.56568115]
[0.56091254]
[0.56493203]
[0.55995796]
[0.56401545]
[0.55917698]
[0.56313307]
[0.55841001]
[0.56239648]
[0.55743654]
[0.56146389]
[0.55667224]
[0.56060545]
[0.55587701]
[0.55985909]
[0.55491379]
[0.55892472]
[0.55415041]
[0.5

[0.31806005]
[0.31322995]
[0.31720226]
[0.31237218]
[0.31634445]
[0.31151438]
[0.31548661]
[0.31065655]
[0.31462874]
[0.3097987]
[0.31377085]
[0.30894081]
[0.31291293]
[0.30808291]
[0.31205498]
[0.30722497]
[0.311197]
[0.30636701]
[0.31033901]
[0.30550903]
[0.30948098]
[0.30465102]
[0.30862293]
[0.30379298]
[0.30776486]
[0.30293492]
[0.30690676]
[0.30207683]
[0.30604864]
[0.30121873]
[0.30519049]
[0.30036059]
[0.30433232]
[0.29950244]
[0.30347413]
[0.29864426]
[0.30261592]
[0.29778606]
[0.30175768]
[0.29692783]
[0.30089942]
[0.29606959]
[0.30004114]
[0.29521132]
[0.29918284]
[0.29435303]
[0.29832451]
[0.29349472]
[0.29746617]
[0.29263639]
[0.2966078]
[0.29177804]
[0.29574942]
[0.29091967]
[0.29489102]
[0.29006129]
[0.29403259]
[0.28920288]
[0.29317415]
[0.28834445]
[0.29231569]
[0.287486]
[0.29145721]
[0.28662754]
[0.29059871]
[0.28576906]
[0.2897402]
[0.28491056]
[0.28888166]
[0.28405204]
[0.28802312]
[0.28319351]
[0.28716455]
[0.28233495]
[0.28630597]
[0.28147639]
[0.28544737]
[0.280

[0.02498914]
[0.028954]
[0.02413275]
[0.02809758]
[0.02327636]
[0.02724116]
[0.02241998]
[0.02638474]
[0.0215636]
[0.02552833]
[0.02070722]
[0.02467192]
[0.01985085]
[0.02381551]
[0.01899448]
[0.02295911]
[0.01813811]
[0.02210271]
[0.01728174]
[0.02124631]
[0.01642538]
[0.02038991]
[0.01556902]
[0.01953351]
[0.01471266]
[0.01867712]
[0.0138563]
[0.01782072]
[0.01299994]
[0.01696433]
[0.01214358]
[0.01610794]
[0.01128723]
[0.01525156]
[0.01043088]
[0.01439517]
[0.00957453]
[0.01353878]
[0.00871817]
[0.0126824]
[0.00786182]
[0.01182601]
[0.00700547]
[0.01096962]
[0.00614912]
[0.01011324]
[0.00529277]
[0.00925686]
[0.00443642]
[0.00840047]
[0.00358007]
[0.00754408]
[0.00272372]
[0.0066877]
[0.00186737]
[0.00583131]
[0.00101101]
[0.00497492]
[0.00015466]
[0.00411853]
[-0.0007017]
[0.00326214]
[-0.00155805]
[0.00240575]
[-0.00241441]
[0.00154936]
[-0.00327077]
[0.00069296]
[-0.00412714]
[-0.00016344]
[-0.0049835]
[-0.00101984]
[-0.00583987]
[-0.00187624]
[-0.00669624]
[-0.00273265]
[-0.0075

[-0.23872109]
[-0.24354014]
[-0.23958129]
[-0.24440035]
[-0.2404415]
[-0.24526056]
[-0.24130172]
[-0.24612079]
[-0.24216196]
[-0.24698103]
[-0.24302221]
[-0.24784129]
[-0.24388247]
[-0.24870156]
[-0.24474275]
[-0.24956184]
[-0.24560304]
[-0.25042213]
[-0.24646334]
[-0.25128244]
[-0.24732365]
[-0.25214276]
[-0.24818398]
[-0.25300309]
[-0.24904432]
[-0.25386344]
[-0.24990467]
[-0.25472379]
[-0.25076504]
[-0.25558416]
[-0.25162541]
[-0.25644455]
[-0.2524858]
[-0.25730494]
[-0.25334621]
[-0.25816535]
[-0.25420662]
[-0.25902577]
[-0.25506705]
[-0.2598862]
[-0.25592749]
[-0.26074664]
[-0.25678794]
[-0.2616071]
[-0.2576484]
[-0.26246757]
[-0.25850887]
[-0.26332805]
[-0.25936936]
[-0.26418854]
[-0.26022986]
[-0.26504904]
[-0.26109037]
[-0.26590956]
[-0.26195089]
[-0.26677008]
[-0.26281143]
[-0.26763062]
[-0.26367197]
[-0.26849117]
[-0.26453253]
[-0.26935173]
[-0.2653931]
[-0.2702123]
[-0.26625367]
[-0.27107289]
[-0.26711426]
[-0.27193348]
[-0.26797487]
[-0.27279409]
[-0.26883548]
[-0.2736547]


[-0.49431883]
[-0.49902468]
[-0.49508823]
[-0.49991224]
[-0.49591821]
[-0.50081804]
[-0.49689875]
[-0.50159136]
[-0.49764325]
[-0.50249936]
[-0.49850814]
[-0.50337912]
[-0.49946018]
[-0.50416866]
[-0.50023179]
[-0.5050556]
[-0.50106161]
[-0.50596095]
[-0.5020417]
[-0.50673439]
[-0.50278755]
[-0.50764064]
[-0.50364859]
[-0.50852334]
[-0.50460446]
[-0.5093105]
[-0.50537471]
[-0.51019715]
[-0.50620309]
[-0.51110291]
[-0.50718364]
[-0.51187601]
[-0.50792711]
[-0.51278503]
[-0.50879449]
[-0.51366184]
[-0.50974305]
[-0.51445304]
[-0.510516]
[-0.51533944]
[-0.51134547]
[-0.51624393]
[-0.51232474]
[-0.51701777]
[-0.51307178]
[-0.51792256]
[-0.51393013]
[-0.51880665]
[-0.51488791]
[-0.51959255]
[-0.51565725]
[-0.52047904]
[-0.51648496]
[-0.52138414]
[-0.51746491]
[-0.52215763]
[-0.51820793]
[-0.52306726]
[-0.5190778]
[-0.52394102]
[-0.52002239]
[-0.52473431]
[-0.52079614]
[-0.52562103]
[-0.52162719]
[-0.52652342]
[-0.52260436]
[-0.52729857]
[-0.52335509]
[-0.52819933]
[-0.52420615]
[-0.52908809

[-0.75794119]
[-0.75399204]
[-0.75884721]
[-0.75496069]
[-0.75962772]
[-0.75567871]
[-0.76053332]
[-0.75664708]
[-0.76131411]
[-0.75736523]
[-0.76221929]
[-0.75833332]
[-0.76300036]
[-0.75905163]
[-0.76390512]
[-0.76001943]
[-0.76468647]
[-0.76073789]
[-0.76559082]
[-0.76170539]
[-0.76637246]
[-0.76242401]
[-0.76727638]
[-0.76339122]
[-0.76805832]
[-0.76411001]
[-0.76896181]
[-0.76507691]
[-0.76974405]
[-0.76579588]
[-0.77064711]
[-0.76676247]
[-0.77142966]
[-0.76748163]
[-0.77233228]
[-0.76844791]
[-0.77311514]
[-0.76916725]
[-0.77401733]
[-0.77013321]
[-0.77480051]
[-0.77085275]
[-0.77570225]
[-0.7718184]
[-0.77648576]
[-0.77253813]
[-0.77738706]
[-0.77350346]
[-0.77817089]
[-0.7742234]
[-0.77907175]
[-0.7751884]
[-0.7798559]
[-0.77590855]
[-0.78075632]
[-0.77687322]
[-0.7815408]
[-0.77759359]
[-0.78244078]
[-0.77855792]
[-0.78322559]
[-0.77927852]
[-0.78412512]
[-0.78024251]
[-0.78491028]
[-0.78096334]
[-0.78580936]
[-0.78192699]
[-0.78659485]
[-0.78264805]
[-0.78749349]
[-0.7836113

[-1.01445492]
[-1.01054418]
[-1.01530823]
[-1.01144548]
[-1.01609163]
[-1.01216114]
[-1.01696684]
[-1.01308411]
[-1.01778875]
[-1.01387707]
[-1.01864259]
[-1.0147803]
[-1.01942554]
[-1.01549581]
[-1.02030065]
[-1.01641739]
[-1.02112331]
[-1.01721369]
[-1.02197573]
[-1.0181126]
[-1.02276044]
[-1.01883275]
[-1.02363419]
[-1.01974954]
[-1.02445768]
[-1.02055144]
[-1.02530758]
[-1.02144172]
[-1.02609728]
[-1.02217308]
[-1.02696795]
[-1.02308376]
[-1.02778881]
[-1.02388348]
[-1.02863904]
[-1.0247717]
[-1.02943133]
[-1.02550934]
[-1.03030022]
[-1.026418]
[-1.03111752]
[-1.02721094]
[-1.03197]
[-1.02810311]
[-1.03276156]
[-1.02884029]
[-1.0336304]
[-1.02974826]
[-1.03444775]
[-1.03054258]
[-1.03529933]
[-1.03143113]
[-1.0360934]
[-1.03217421]
[-1.03696053]
[-1.03308085]
[-1.03777385]
[-1.03386694]
[-1.03862816]
[-1.03476004]
[-1.03942214]
[-1.03550403]
[-1.04028885]
[-1.03640965]
[-1.04110154]
[-1.03719553]
[-1.04195558]
[-1.03808645]
[-1.04275151]
[-1.0388354]
[-1.04361671]
[-1.03973948]
[-1

[-1.25616366]
[-1.26085495]
[-1.25698706]
[-1.26167829]
[-1.25781045]
[-1.26250162]
[-1.25863383]
[-1.26332495]
[-1.2594572]
[-1.26414827]
[-1.26028057]
[-1.26497157]
[-1.26110393]
[-1.26579487]
[-1.26192727]
[-1.26661817]
[-1.26275061]
[-1.26744145]
[-1.26357394]
[-1.26826473]
[-1.26439727]
[-1.26908799]
[-1.26522058]
[-1.26991125]
[-1.26604389]
[-1.27073451]
[-1.26686719]
[-1.27155775]
[-1.26769048]
[-1.27238099]
[-1.26851377]
[-1.27320422]
[-1.26933704]
[-1.27402744]
[-1.27016031]
[-1.27485065]
[-1.27098357]
[-1.27567386]
[-1.27180683]
[-1.27649706]
[-1.27263007]
[-1.27732025]
[-1.27345331]
[-1.27814343]
[-1.27427654]
[-1.27896661]
[-1.27509976]
[-1.27978978]
[-1.27592298]
[-1.28061294]
[-1.27674619]
[-1.2814361]
[-1.27756939]
[-1.28225925]
[-1.27839259]
[-1.28308239]
[-1.27921577]
[-1.28390552]
[-1.28003895]
[-1.28472865]
[-1.28086213]
[-1.28555177]
[-1.2816853]
[-1.28637489]
[-1.28250846]
[-1.28719799]
[-1.28333161]
[-1.2880211]
[-1.28415476]
[-1.28884419]
[-1.2849779]
[-1.2896672

[-1.50685168]
[-1.50299833]
[-1.50767425]
[-1.50382097]
[-1.50849683]
[-1.5046436]
[-1.5093194]
[-1.50546624]
[-1.51014198]
[-1.50628888]
[-1.51096455]
[-1.50711152]
[-1.51178713]
[-1.50793416]
[-1.51260971]
[-1.5087568]
[-1.51343229]
[-1.50957945]
[-1.51425487]
[-1.51040209]
[-1.51507745]
[-1.51122474]
[-1.51590004]
[-1.51204739]
[-1.51672262]
[-1.51287004]
[-1.51754521]
[-1.51369269]
[-1.5183678]
[-1.51451534]
[-1.51919038]
[-1.515338]
[-1.52001298]
[-1.51616065]
[-1.52083557]
[-1.51698331]
[-1.52165816]
[-1.51780597]
[-1.52248076]
[-1.51862863]
[-1.52330335]
[-1.5194513]
[-1.52412595]
[-1.52027396]
[-1.52494855]
[-1.52109663]
[-1.52577115]
[-1.5219193]
[-1.52659375]
[-1.52274197]
[-1.52741636]
[-1.52356464]
[-1.52823896]
[-1.52438731]
[-1.52906157]
[-1.52520999]
[-1.52988418]
[-1.52603266]
[-1.53070679]
[-1.52685534]
[-1.5315294]
[-1.52767802]
[-1.53235202]
[-1.52850071]
[-1.53317463]
[-1.52932339]
[-1.53399725]
[-1.53014608]
[-1.53481987]
[-1.53096877]
[-1.53564249]
[-1.53179146]
[

[-1.75707083]
[-1.75324127]
[-1.75789478]
[-1.75406529]
[-1.75871874]
[-1.75488931]
[-1.75954271]
[-1.75571334]
[-1.76036668]
[-1.75653738]
[-1.76119066]
[-1.75736142]
[-1.76201465]
[-1.75818547]
[-1.76283864]
[-1.75900953]
[-1.76366264]
[-1.75983359]
[-1.76448665]
[-1.76065766]
[-1.76531067]
[-1.76148174]
[-1.76613469]
[-1.76230582]
[-1.76695872]
[-1.76312991]
[-1.76778275]
[-1.763954]
[-1.76860679]
[-1.7647781]
[-1.76943084]
[-1.76560221]
[-1.7702549]
[-1.76642633]
[-1.77107896]
[-1.76725045]
[-1.77190303]
[-1.76807458]
[-1.7727271]
[-1.76889871]
[-1.77355118]
[-1.76972285]
[-1.77437527]
[-1.770547]
[-1.77519936]
[-1.77137115]
[-1.77602347]
[-1.77219532]
[-1.77684757]
[-1.77301948]
[-1.77767169]
[-1.77384366]
[-1.77849581]
[-1.77466783]
[-1.77931994]
[-1.77549202]
[-1.78014407]
[-1.77631621]
[-1.78096821]
[-1.77714041]
[-1.78179236]
[-1.77796462]
[-1.78261651]
[-1.77878883]
[-1.78344067]
[-1.77961304]
[-1.78426484]
[-1.78043727]
[-1.78508901]
[-1.7812615]
[-1.78591319]
[-1.78208573]


[-2.00725655]
[-2.01189848]
[-2.00808161]
[-2.01272351]
[-2.00890666]
[-2.01354854]
[-2.00973172]
[-2.01437357]
[-2.01055678]
[-2.0151986]
[-2.01138183]
[-2.01602363]
[-2.01220689]
[-2.01684866]
[-2.01303194]
[-2.0176737]
[-2.013857]
[-2.01849872]
[-2.01468205]
[-2.01932375]
[-2.01550711]
[-2.02014878]
[-2.01633216]
[-2.02097381]
[-2.01715722]
[-2.02179884]
[-2.01798227]
[-2.02262387]
[-2.01880732]
[-2.0234489]
[-2.01963237]
[-2.02427392]
[-2.02045743]
[-2.02509895]
[-2.02128248]
[-2.02592398]
[-2.02210753]
[-2.026749]
[-2.02293258]
[-2.02757403]
[-2.02375763]
[-2.02839905]
[-2.02458268]
[-2.02922408]
[-2.02540772]
[-2.0300491]
[-2.02623277]
[-2.03087412]
[-2.02705782]
[-2.03169914]
[-2.02788287]
[-2.03252416]
[-2.02870791]
[-2.03334919]
[-2.02953296]
[-2.03417421]
[-2.030358]
[-2.03499923]
[-2.03118304]
[-2.03582424]
[-2.03200809]
[-2.03664926]
[-2.03283313]
[-2.03747428]
[-2.03365817]
[-2.0382993]
[-2.03448321]
[-2.03912431]
[-2.03530825]
[-2.03994933]
[-2.03613329]
[-2.04077434]
[-2

[-2.26705065]
[-2.27168474]
[-2.26787485]
[-2.27250891]
[-2.26869905]
[-2.27333308]
[-2.26952324]
[-2.27415724]
[-2.27034743]
[-2.2749814]
[-2.27117161]
[-2.27580556]
[-2.27199579]
[-2.27662971]
[-2.27281996]
[-2.27745386]
[-2.27364413]
[-2.278278]
[-2.2744683]
[-2.27910213]
[-2.27529246]
[-2.27992627]
[-2.27611662]
[-2.2807504]
[-2.27694077]
[-2.28157452]
[-2.27776491]
[-2.28239864]
[-2.27858906]
[-2.28322275]
[-2.27941319]
[-2.28404686]
[-2.28023733]
[-2.28487097]
[-2.28106146]
[-2.28569507]
[-2.28188558]
[-2.28651916]
[-2.2827097]
[-2.28734326]
[-2.28353381]
[-2.28816734]
[-2.28435792]
[-2.28899142]
[-2.28518203]
[-2.2898155]
[-2.28600613]
[-2.29063958]
[-2.28683023]
[-2.29146364]
[-2.28765432]
[-2.29228771]
[-2.28847841]
[-2.29311177]
[-2.28930249]
[-2.29393582]
[-2.29012657]
[-2.29475987]
[-2.29095064]
[-2.29558392]
[-2.29177471]
[-2.29640796]
[-2.29259877]
[-2.29723199]
[-2.29342283]
[-2.29805602]
[-2.29424689]
[-2.29888005]
[-2.29507094]
[-2.29970407]
[-2.29589498]
[-2.30052809]

[-2.51624773]
[-2.51244522]
[-2.5170704]
[-2.51326792]
[-2.51789306]
[-2.51409061]
[-2.51871572]
[-2.51491329]
[-2.51953838]
[-2.51573597]
[-2.52036103]
[-2.51655865]
[-2.52118367]
[-2.51738132]
[-2.52200631]
[-2.51820398]
[-2.52282894]
[-2.51902664]
[-2.52365157]
[-2.51984929]
[-2.52447419]
[-2.52067194]
[-2.52529681]
[-2.52149458]
[-2.52611942]
[-2.52231722]
[-2.52694203]
[-2.52313985]
[-2.52776463]
[-2.52396248]
[-2.52858723]
[-2.5247851]
[-2.52940982]
[-2.52560772]
[-2.5302324]
[-2.52643033]
[-2.53105498]
[-2.52725294]
[-2.53187756]
[-2.52807554]
[-2.53270013]
[-2.52889813]
[-2.53352269]
[-2.52972072]
[-2.53434525]
[-2.53054331]
[-2.5351678]
[-2.53136588]
[-2.53599035]
[-2.53218846]
[-2.53681289]
[-2.53301103]
[-2.53763543]
[-2.53383359]
[-2.53845796]
[-2.53465615]
[-2.53928049]
[-2.5354787]
[-2.54010301]
[-2.53630125]
[-2.54092553]
[-2.53712379]
[-2.54174804]
[-2.53794632]
[-2.54257054]
[-2.53876886]
[-2.54339304]
[-2.53959138]
[-2.54421554]
[-2.5404139]
[-2.54503803]
[-2.54123642

[-2.77461853]
[-2.77923425]
[-2.77543957]
[-2.78005526]
[-2.7762606]
[-2.78087626]
[-2.77708163]
[-2.78169727]
[-2.77790265]
[-2.78251826]
[-2.77872367]
[-2.78333925]
[-2.77954469]
[-2.78416024]
[-2.7803657]
[-2.78498122]
[-2.7811867]
[-2.7858022]
[-2.7820077]
[-2.78662317]
[-2.78282869]
[-2.78744414]
[-2.78364968]
[-2.7882651]
[-2.78447067]
[-2.78908606]
[-2.78529165]
[-2.78990701]
[-2.78611262]
[-2.79072796]
[-2.78693359]
[-2.7915489]
[-2.78775456]
[-2.79236984]
[-2.78857552]
[-2.79319077]
[-2.78939647]
[-2.7940117]
[-2.79021742]
[-2.79483262]
[-2.79103837]
[-2.79565354]
[-2.79185931]
[-2.79647445]
[-2.79268024]
[-2.79729536]
[-2.79350117]
[-2.79811626]
[-2.7943221]
[-2.79893716]
[-2.79514302]
[-2.79975806]
[-2.79596393]
[-2.80057894]
[-2.79678484]
[-2.80139983]
[-2.79760575]
[-2.80222071]
[-2.79842665]
[-2.80304158]
[-2.79924755]
[-2.80386245]
[-2.80006844]
[-2.80468331]
[-2.80088932]
[-2.80550417]
[-2.8017102]
[-2.80632503]
[-2.80253108]
[-2.80714588]
[-2.80335195]
[-2.80796672]
[-

[-3.02777962]
[-3.02399099]
[-3.02859917]
[-3.02481057]
[-3.02941873]
[-3.02563014]
[-3.03023828]
[-3.02644971]
[-3.03105782]
[-3.02726927]
[-3.03187736]
[-3.02808882]
[-3.03269689]
[-3.02890837]
[-3.03351642]
[-3.02972792]
[-3.03433595]
[-3.03054746]
[-3.03515547]
[-3.031367]
[-3.03597498]
[-3.03218653]
[-3.03679449]
[-3.03300606]
[-3.037614]
[-3.03382558]
[-3.0384335]
[-3.0346451]
[-3.03925299]
[-3.03546461]
[-3.04007249]
[-3.03628412]
[-3.04089197]
[-3.03710363]
[-3.04171145]
[-3.03792313]
[-3.04253093]
[-3.03874262]
[-3.0433504]
[-3.03956211]
[-3.04416987]
[-3.04038159]
[-3.04498933]
[-3.04120107]
[-3.04580879]
[-3.04202055]
[-3.04662825]
[-3.04284002]
[-3.04744769]
[-3.04365949]
[-3.04826714]
[-3.04447895]
[-3.04908658]
[-3.0452984]
[-3.04990601]
[-3.04611785]
[-3.05072544]
[-3.0469373]
[-3.05154487]
[-3.04775674]
[-3.05236429]
[-3.04857618]
[-3.0531837]
[-3.04939561]
[-3.05400311]
[-3.05021504]
[-3.05482252]
[-3.05103446]
[-3.05564192]
[-3.05185388]
[-3.05646132]
[-3.0526733]
[-3

[-3.28570416]
[-3.28192026]
[-3.28652221]
[-3.28273832]
[-3.28734025]
[-3.28355638]
[-3.28815829]
[-3.28437443]
[-3.28897632]
[-3.28519248]
[-3.28979435]
[-3.28601052]
[-3.29061238]
[-3.28682856]
[-3.2914304]
[-3.28764659]
[-3.29224841]
[-3.28846461]
[-3.29306642]
[-3.28928264]
[-3.29388443]
[-3.29010065]
[-3.29470243]
[-3.29091867]
[-3.29552042]
[-3.29173668]
[-3.29633841]
[-3.29255468]
[-3.2971564]
[-3.29337268]
[-3.29797438]
[-3.29419067]
[-3.29879235]
[-3.29500866]
[-3.29961033]
[-3.29582664]
[-3.30042829]
[-3.29664462]
[-3.30124625]
[-3.2974626]
[-3.30206421]
[-3.29828057]
[-3.30288216]
[-3.29909853]
[-3.30370011]
[-3.29991649]
[-3.30451805]
[-3.30073444]
[-3.30533599]
[-3.30155239]
[-3.30615392]
[-3.30237034]
[-3.30697185]
[-3.30318828]
[-3.30778977]
[-3.30400621]
[-3.30860769]
[-3.30482415]
[-3.3094256]
[-3.30564207]
[-3.31024351]
[-3.30645999]
[-3.31106142]
[-3.30727791]
[-3.31187932]
[-3.30809582]
[-3.31269721]
[-3.30891373]
[-3.3135151]
[-3.30973163]
[-3.31433298]
[-3.3105495

[-3.53365699]
[-3.53825413]
[-3.53447359]
[-3.53907072]
[-3.53529019]
[-3.5398873]
[-3.53610678]
[-3.54070388]
[-3.53692336]
[-3.54152045]
[-3.53773995]
[-3.54233702]
[-3.53855652]
[-3.54315359]
[-3.5393731]
[-3.54397015]
[-3.54018967]
[-3.5447867]
[-3.54100623]
[-3.54560325]
[-3.54182279]
[-3.5464198]
[-3.54263935]
[-3.54723634]
[-3.5434559]
[-3.54805288]
[-3.54427244]
[-3.54886941]
[-3.54508898]
[-3.54968594]
[-3.54590552]
[-3.55050246]
[-3.54672205]
[-3.55131898]
[-3.54753858]
[-3.55213549]
[-3.5483551]
[-3.552952]
[-3.54917162]
[-3.55376851]
[-3.54998813]
[-3.55458501]
[-3.55080464]
[-3.5554015]
[-3.55162115]
[-3.556218]
[-3.55243765]
[-3.55703448]
[-3.55325414]
[-3.55785096]
[-3.55407064]
[-3.55866744]
[-3.55488712]
[-3.55948392]
[-3.5557036]
[-3.56030038]
[-3.55652008]
[-3.56111685]
[-3.55733655]
[-3.56193331]
[-3.55815302]
[-3.56274976]
[-3.55896949]
[-3.56356621]
[-3.55978594]
[-3.56438266]
[-3.5606024]
[-3.5651991]
[-3.56141885]
[-3.56601554]
[-3.56223529]
[-3.56683197]
[-3.56

In [55]:
print(weights)
print(bias)

[[ 9.35774342]
 [ 0.96217188]
 [-1.12680939]
 [-0.4507052 ]
 [ 0.49852327]
 [-0.13769575]
 [ 0.37542456]
 [-1.45852054]]
[-3.57693053]


# Predict Points

In [56]:
pred = sigmoid(np.dot(X1, weights) + bias)
pred = pred.astype(int)

In [57]:
pred

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
    

In [58]:
accuracy_score(y1, pred)*100

55.59701492537313