In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from keras.models import Sequential
from keras.layers import Dense
df = pd.read_csv('diabetes.csv',sep = ',')
# starting web3 operations
import numpy as np
import json
from web3 import Web3
import time
ganache_url = "HTTP://127.0.0.1:8545"
web3 = Web3(Web3.HTTPProvider(ganache_url))
web3.isConnected()

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


False

In [2]:
abi = json.loads('[{ "inputs": [], "name": "add_print", "outputs": [ { "internalType": "int256", "name": "x", "type": "int256" }, { "internalType": "int256", "name": "y", "type": "int256" } ], "stateMutability": "view", "type": "function" }, { "inputs": [ { "internalType": "int256[]", "name": "input", "type": "int256[]" }, { "internalType": "int256[]", "name": "w", "type": "int256[]" }, { "internalType": "int256[]", "name": "b", "type": "int256[]" } ], "name": "compute_IXWB", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "a", "type": "int256" }, { "internalType": "int256", "name": "b", "type": "int256" }, { "internalType": "int256", "name": "c", "type": "int256" }, { "internalType": "int256", "name": "d", "type": "int256" } ], "name": "compute_addition", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "x", "type": "int256" }, { "internalType": "int256", "name": "y", "type": "int256" } ], "name": "compute_lcm", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "d", "type": "int256" } ], "name": "compute_sigmoid", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "lcm_print", "outputs": [ { "internalType": "int256", "name": "", "type": "int256" } ], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "predict_print", "outputs": [ { "internalType": "int256", "name": "", "type": "int256" } ], "stateMutability": "view", "type": "function" }]')
cont_address = "0xFD9fFdE09432258482C532d80bBDB5c4577dc2DF"

account1 = "0x37bfB436392DaAE0E91EdcD9c4128FBcADF3919d"
private_key1 = "e72044de2331844a3c0232dc23d43fb8ca4f555854b4da07e2fb530d003e5e2d"
account2 = "0xfbD8f1F5878b0b5b3E627e7cc14617b05B582867"
private_key2="56c8f569b23a423f9d66d46f86f7ada7ba0d28dfba03c34f661bb15358b042bb"


In [3]:
df['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']*100
df.DiabetesPedigreeFunction = df.DiabetesPedigreeFunction.astype(int)
df.BMI = df.BMI.astype(int) 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   

   DiabetesPedigreeFunction  Age  Outcome  
0                        62   50        1  
1                        35   31        0  
2                        67   32        1  
3                        16   21        0  
4                       228   33        1

In [4]:
dataset = df.to_numpy()

X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]

In [5]:
print(X[:5])
print(y[:5])

[[  6 148  72  35   0  33  62  50]
 [  1  85  66  29   0  26  35  31]
 [  8 183  64   0   0  23  67  32]
 [  1  89  66  23  94  28  16  21]
 [  0 137  40  35 168  43 228  33]]
[1 0 1 0 1]


In [6]:
# define the keras model
model = Sequential()
# model.add(Dense(12, input_dim=8, activation='sigmoid'))
# model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [7]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
4
...
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpzpxdy4xe.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpzpxdy4xe.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
50/50 [==============================] - 16s 660us/step - loss: 27.6949 - accuracy: 0.6315
Epoch 2/150
50/50 [==============================] - 0s 530us/step - loss: 20.3595 - accuracy: 0.6015
Epoch 3/150
50/50 [==============================] - 0s 530us/step - loss: 23.9690 - accuracy: 0.5034
Epoch 4/150
50/50 [==============================] - 0s 530us/step - loss: 20.3117 - accu

50/50 [==============================] - 0s 469us/step - loss: 0.8783 - accuracy: 0.6515
Epoch 73/150
50/50 [==============================] - 0s 469us/step - loss: 0.7204 - accuracy: 0.7122
Epoch 74/150
50/50 [==============================] - 0s 476us/step - loss: 0.8178 - accuracy: 0.6802
Epoch 75/150
50/50 [==============================] - 0s 500us/step - loss: 0.7247 - accuracy: 0.6875
Epoch 76/150
50/50 [==============================] - 0s 489us/step - loss: 0.7228 - accuracy: 0.6827
Epoch 77/150
50/50 [==============================] - 0s 490us/step - loss: 0.7468 - accuracy: 0.6803
Epoch 78/150
50/50 [==============================] - 0s 505us/step - loss: 0.6456 - accuracy: 0.7013
Epoch 79/150
50/50 [==============================] - 0s 507us/step - loss: 0.7201 - accuracy: 0.6779
Epoch 80/150
50/50 [==============================] - 0s 507us/step - loss: 0.6166 - accuracy: 0.7202
Epoch 81/150
50/50 [==============================] - 0s 474us/step - loss: 0.6574 - accuracy: 

In [9]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (10, 1)                   9         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
4
...
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

16/16 [==============================] - 0s 639us/step - loss: 0.5721 - accuracy: 0.7220
Accuracy: 72.20


In [11]:
for layer in model.layers: 
    print(layer.get_config())
    print(layer.get_weights())
    
    w = layer.get_weights()

{'name': 'dense', 'trainable': True, 'dtype': 'float32', 'units': 1, 'activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
[array([[ 0.13420492],
       [ 0.01372297],
       [-0.02598029],
       [-0.0096017 ],
       [ 0.00154922],
       [ 0.02458862],
       [ 0.00475701],
       [-0.01920895]], dtype=float32), array([-1.2286978], dtype=float32)]


In [12]:
weights = w[0]
bias = w[1]

In [13]:
print(X1[0])

[  2 117  90  19  71  25  31  21]


In [14]:
predictions = model.predict(X1)
# predictions

In [15]:
# for i in range(len(predictions)):
#     if(predictions[i]>=.5):
#         print(i)

In [16]:

rounded= [round(x[0]) for x in predictions]
# rounded

In [19]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
accuracy_score(y1, rounded)

0.7313432835820896

In [20]:
print(classification_report(y1,rounded))

              precision    recall  f1-score   support

           0       0.75      0.91      0.82       182
           1       0.65      0.35      0.45        86

    accuracy                           0.73       268
   macro avg       0.70      0.63      0.64       268
weighted avg       0.72      0.73      0.70       268



In [21]:
print(rounded)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


In [22]:
print(y1[:10])

[0 0 1 0 0 0 1 0 0 0]


In [23]:
w = np.zeros((8,2))
for i in range(weights.shape[0]):
    w[i][0] = int(weights[i][0]*1000)
    w[i][1] = 1000
w


array([[ 134., 1000.],
       [  13., 1000.],
       [ -25., 1000.],
       [  -9., 1000.],
       [   1., 1000.],
       [  24., 1000.],
       [   4., 1000.],
       [ -19., 1000.]])

In [24]:
b = []
b.append(int(bias*1000))
b.append(1000)

In [25]:
def compute_lcm(x, y):
   # choose the greater number
    if (x > y):
        greater = x
    else:
        greater = y
    while(True):
        if((greater % x == 0) and (greater % y == 0)):
            lcm = greater
            break
        greater += 1
    return lcm

In [26]:
def addition(a,b,c,d):
    den = compute_lcm(b,d)
#     den = b*d
    num = ((den/b)*a) + ((den/d)*c)
#     print(num,den)
    return float(num),float(den)
        

In [27]:
def IXWB(inputs,w,b):
    num=0
    den=0
    out = np.zeros((inputs.shape[0],1))
    for i in range(inputs.shape[0]):
#     for i in range(10):
#         print(inputs[i][0],w)
        for j in range(inputs.shape[1]):
            num = num + inputs[i][j]*w[j][0]
            den = w[0][1]
        num,den = addition(num,den,b[0],b[1])
        out[i][0] = num
#         out[i][1] = den
        num =0
        den =0
    return out

In [28]:
print(X1[0])
print(b[0])

[  2 117  90  19  71  25  31  21]
-1228


In [29]:
test = IXWB(X1,w,b)
# print(test)

In [30]:
# for i in range(len(test)):
#     if(test[i][0]>0):
#         print(i)

In [31]:
def sigmoidfrac(x):
    if(x>=0):
        return 1
    else:
        return 0

In [32]:
out = []
for i in range(test.shape[0]):
    out.append(sigmoidfrac(test[i][0]))
# out

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, out)

0.7164179104477612

In [34]:

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
confusion_matrix(y1,out)

array([[167,  15],
       [ 61,  25]], dtype=int64)

In [35]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cf_matrix = confusion_matrix(y1,out)
sns.heatmap(cf_matrix/np.sum(cf_matrix), annot=True, 
            fmt='.2%', cmap='Blues')

NameError: name 'sns' is not defined

In [ ]:
weight = new_weight.tolist()

In [ ]:
print(weights)
print(bias)

In [ ]:
# # def sigmoid_tx(acc,pk,X_input,weight,bias,cont_address,abi):
# contract = web3.eth.contract(address=cont_address,abi=abi)
# # getting IXWB
# nonce = web3.eth.getTransactionCount(account1)
# print(type(X_input),type(weight),type(bias))
# tx_IXWB = contract.functions.compute_IXWB(X_input,weight,bias
#     ).buildTransaction({
#     'gas': 100000,
#     'gasPrice': web3.toWei('1', 'gwei'),
#     'from': account1,
#     'nonce': nonce
#     }) 
# signed_txn = web3.eth.account.signTransaction(tx_IXWB, private_key=private_key1)
# start_time = time.time()
# tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
# tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
# end_time = time.time()
# print(end_time -start_time)
# out_num,out_den = contract.functions.add_print().call()

# # getting sigmoid
# nonce= web3.eth.getTransactionCount(account1)
# tx_sigmoid = contract.functions.compute_sigmoid(
#     out_num
#      ).buildTransaction({
#     'gas': 70000,
#     'gasPrice': web3.toWei('1', 'gwei'),
#     'from': account1,
#     'nonce': nonce
#     }) 
# signed_txn = web3.eth.account.signTransaction(tx_sigmoid, private_key=private_key1)
# start_time = time.time()
# tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
# tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
# end_time = time.time()
# print(end_time -start_time)
# pred = contract.functions.predict_print().call()
# #     return pred

In [ ]:
# print (X1, w,b,)
# b = b.tolist()
nw  = w[:,0].astype(int)
nw = nw.tolist()
print (X1, nw,b)

In [ ]:
pred =[]
IXWB_time=[]
sigmoid_time=[]
IXWB_gasuse=[]
sigmoid_gasuse=[]

for i in range(X1.shape[0]):
    # getting IXWB
    inputs = X1[i].tolist()
#     pred.append(sigmoid_tx(account1, private_key1,inputs,weight,bias,cont_address,abi))
    contract = web3.eth.contract(address=cont_address,abi=abi)
#     print(inputs,nw,b)
    nonce = web3.eth.getTransactionCount(account2)
#     print(type(inputs),type(nw),type(b))
    tx_IXWB = contract.functions.compute_IXWB(
        inputs,nw,b
        ).buildTransaction({
        'gas': 1000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account2,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(tx_IXWB, private_key=private_key2)
    start_time = time.time()
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    end_time = time.time()
    IXWB_time.append(end_time -start_time)
    IXWB_gasuse.append(tx_receipt.gasUsed)
    out_num,out_den = contract.functions.add_print().call()

    # getting sigmoid
    nonce= web3.eth.getTransactionCount(account2)
    tx_sigmoid = contract.functions.compute_sigmoid(
        out_num
         ).buildTransaction({
        'gas': 1000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account2,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(tx_sigmoid, private_key=private_key2)
    start_time = time.time()
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    end_time = time.time()
    sigmoid_time.append(end_time -start_time)
    sigmoid_gasuse.append(tx_receipt.gasUsed)
    pred.append(contract.functions.predict_print().call())
    inputs.clear()
   

In [ ]:
print(pred)

In [ ]:
print(accuracy_score(y1, pred))

In [ ]:
print(sigmoid_time)
print(sigmoid_gasuse)

In [ ]:
import pandas as pd
df = pd.DataFrame(sigmoid_time)
df.to_csv("testfile",index=False)


In [ ]:
# a = pd.DataFrame(sigmoid_time)
# a.to_csv("sigmoid_time_ganache.csv",index=False)
# a = pd.DataFrame(sigmoid_gasuse)
# a.to_csv("sigmoid_gasuse_ganache.csv",index=False)
# a = pd.DataFrame(IXWB_time)
# a.to_csv("IXWB_time_ganache.csv",index=False)
# a = pd.DataFrame(IXWB_gasuse)
# a.to_csv("IXWB_gasuse_ganache.csv",index=False)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cf_matrix = confusion_matrix(y1,pred)

In [ ]:
import seaborn as sns
sns.heatmap(cf_matrix, annot=True)

In [ ]:
sns.heatmap(cf_matrix/np.sum(cf_matrix), annot=True, 
            fmt='.2%', cmap='Blues')

In [ ]:
print(classification_report(y1,pred))