In [488]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from keras.models import Sequential
from keras.layers import Dense
df = pd.read_csv('diabetes.csv',sep = ',')
# starting web3 operations
import numpy as np
import json
from web3 import Web3
import time
ganache_url = "HTTP://127.0.0.1:8545"
web3 = Web3(Web3.HTTPProvider(ganache_url))
web3.isConnected()

True

In [489]:
abi = json.loads('[{ "inputs": [], "name": "add_print", "outputs": [ { "internalType": "int256", "name": "x", "type": "int256" }, { "internalType": "int256", "name": "y", "type": "int256" } ], "stateMutability": "view", "type": "function" }, { "inputs": [ { "internalType": "int256[]", "name": "input", "type": "int256[]" }, { "internalType": "int256[]", "name": "w", "type": "int256[]" }, { "internalType": "int256[]", "name": "b", "type": "int256[]" } ], "name": "compute_IXWB", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "a", "type": "int256" }, { "internalType": "int256", "name": "b", "type": "int256" }, { "internalType": "int256", "name": "c", "type": "int256" }, { "internalType": "int256", "name": "d", "type": "int256" } ], "name": "compute_addition", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "x", "type": "int256" }, { "internalType": "int256", "name": "y", "type": "int256" } ], "name": "compute_lcm", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "d", "type": "int256" } ], "name": "compute_sigmoid", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "lcm_print", "outputs": [ { "internalType": "int256", "name": "", "type": "int256" } ], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "predict_print", "outputs": [ { "internalType": "int256", "name": "", "type": "int256" } ], "stateMutability": "view", "type": "function" }]')
cont_address = "0xFD9fFdE09432258482C532d80bBDB5c4577dc2DF"

account1 = "0x37bfB436392DaAE0E91EdcD9c4128FBcADF3919d"
private_key1 = "e72044de2331844a3c0232dc23d43fb8ca4f555854b4da07e2fb530d003e5e2d"
account2 = "0xfbD8f1F5878b0b5b3E627e7cc14617b05B582867"
private_key2="56c8f569b23a423f9d66d46f86f7ada7ba0d28dfba03c34f661bb15358b042bb"


In [490]:
df['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']*100
df.DiabetesPedigreeFunction = df.DiabetesPedigreeFunction.astype(int)
df.BMI = df.BMI.astype(int) 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   

   DiabetesPedigreeFunction  Age  Outcome  
0                        62   50        1  
1                        35   31        0  
2                        67   32        1  
3                        16   21        0  
4                       228   33        1

In [491]:
dataset = df.to_numpy()

X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]

In [492]:
print(X[:5])
print(y[:5])

[[  6 148  72  35   0  33  62  50]
 [  1  85  66  29   0  26  35  31]
 [  8 183  64   0   0  23  67  32]
 [  1  89  66  23  94  28  16  21]
 [  0 137  40  35 168  43 228  33]]
[1 0 1 0 1]


In [493]:
# define the keras model
model = Sequential()
# model.add(Dense(12, input_dim=8, activation='sigmoid'))
# model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [494]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [495]:
4
...
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
50/50 [==============================] - 1s 538us/step - loss: 47.9136 - accuracy: 0.3297
Epoch 2/150
50/50 [==============================] - 0s 518us/step - loss: 37.2631 - accuracy: 0.3368
Epoch 3/150
50/50 [==============================] - 0s 538us/step - loss: 30.9752 - accuracy: 0.3660
Epoch 4/150
50/50 [==============================] - 0s 518us/step - loss: 23.3883 - accuracy: 0.3790
Epoch 5/150
50/50 [==============================] - 0s 498us/step - loss: 17.3296 - accuracy: 0.4303
Epoch 6/150
50/50 [==============================] - 0s 518us/step - loss: 14.3766 - accuracy: 0.4586
Epoch 7/150
50/50 [==============================] - 0s 498us/step - loss: 12.7127 - accuracy: 0.5047
Epoch 8/150
50/50 [==============================] - 0s 717us/step - loss: 12.9626 - accuracy: 0.5117
Epoch 9/150
50/50 [==============================] - 0s 558us/step - loss: 11.2199 - accuracy: 0.5230
Epoch 10/150
50/50 [==============================] - 0s 458us/step - loss: 11.844

In [496]:
print(model.summary())

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (10, 1)                   9         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None


In [497]:
4
...
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

16/16 [==============================] - 0s 585us/step - loss: 0.5884 - accuracy: 0.7160
Accuracy: 71.60


In [498]:
for layer in model.layers: 
    print(layer.get_config())
    print(layer.get_weights())
    
    w = layer.get_weights()

{'name': 'dense_14', 'trainable': True, 'dtype': 'float32', 'units': 1, 'activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
[array([[ 0.13211168],
       [ 0.01525926],
       [-0.02515939],
       [-0.00679704],
       [ 0.0019308 ],
       [ 0.02504629],
       [ 0.00425911],
       [-0.01824518]], dtype=float32), array([-1.1685565], dtype=float32)]


In [499]:
weights = w[0]
bias = w[1]

In [500]:
print(X1[0])

[  2 117  90  19  71  25  31  21]


In [501]:
predictions = model.predict(X1)
# predictions

In [502]:
# for i in range(len(predictions)):
#     if(predictions[i]>=.5):
#         print(i)

In [503]:

rounded= [round(x[0]) for x in predictions]
# rounded

In [504]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, rounded)

0.7089552238805971

In [505]:
print(rounded)

[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


In [506]:
print(y1[:10])

[0 0 1 0 0 0 1 0 0 0]


In [507]:
w = np.zeros((8,2))
for i in range(weights.shape[0]):
    w[i][0] = int(weights[i][0]*1000)
    w[i][1] = 1000
w


array([[ 132., 1000.],
       [  15., 1000.],
       [ -25., 1000.],
       [  -6., 1000.],
       [   1., 1000.],
       [  25., 1000.],
       [   4., 1000.],
       [ -18., 1000.]])

In [508]:
b = []
b.append(int(bias*1000))
b.append(1000)

In [509]:
def compute_lcm(x, y):
   # choose the greater number
    if (x > y):
        greater = x
    else:
        greater = y
    while(True):
        if((greater % x == 0) and (greater % y == 0)):
            lcm = greater
            break
        greater += 1
    return lcm

In [510]:
def addition(a,b,c,d):
    den = compute_lcm(b,d)
#     den = b*d
    num = ((den/b)*a) + ((den/d)*c)
#     print(num,den)
    return float(num),float(den)
        

In [511]:
def IXWB(inputs,w,b):
    num=0
    den=0
    out = np.zeros((inputs.shape[0],1))
    for i in range(inputs.shape[0]):
#     for i in range(10):
#         print(inputs[i][0],w)
        for j in range(inputs.shape[1]):
            num = num + inputs[i][j]*w[j][0]
            den = w[0][1]
        num,den = addition(num,den,b[0],b[1])
        out[i][0] = num
#         out[i][1] = den
        num =0
        den =0
    return out

In [512]:
print(X1[0])
print(b[0])

[  2 117  90  19  71  25  31  21]
-1168


In [513]:
test = IXWB(X1,w,b)
# print(test)

In [514]:
# for i in range(len(test)):
#     if(test[i][0]>0):
#         print(i)

In [515]:
def sigmoidfrac(x):
    if(x>=0):
        return 1
    else:
        return 0

In [516]:
out = []
for i in range(test.shape[0]):
    out.append(sigmoidfrac(test[i][0]))
# out

In [517]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, out)

0.7388059701492538

In [518]:
weight = new_weight.tolist()

In [519]:
print(weights)
print(bias)

[[ 0.13211168]
 [ 0.01525926]
 [-0.02515939]
 [-0.00679704]
 [ 0.0019308 ]
 [ 0.02504629]
 [ 0.00425911]
 [-0.01824518]]
[-1.1685565]


In [520]:
# # def sigmoid_tx(acc,pk,X_input,weight,bias,cont_address,abi):
# contract = web3.eth.contract(address=cont_address,abi=abi)
# # getting IXWB
# nonce = web3.eth.getTransactionCount(account1)
# print(type(X_input),type(weight),type(bias))
# tx_IXWB = contract.functions.compute_IXWB(X_input,weight,bias
#     ).buildTransaction({
#     'gas': 100000,
#     'gasPrice': web3.toWei('1', 'gwei'),
#     'from': account1,
#     'nonce': nonce
#     }) 
# signed_txn = web3.eth.account.signTransaction(tx_IXWB, private_key=private_key1)
# start_time = time.time()
# tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
# tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
# end_time = time.time()
# print(end_time -start_time)
# out_num,out_den = contract.functions.add_print().call()

# # getting sigmoid
# nonce= web3.eth.getTransactionCount(account1)
# tx_sigmoid = contract.functions.compute_sigmoid(
#     out_num
#      ).buildTransaction({
#     'gas': 70000,
#     'gasPrice': web3.toWei('1', 'gwei'),
#     'from': account1,
#     'nonce': nonce
#     }) 
# signed_txn = web3.eth.account.signTransaction(tx_sigmoid, private_key=private_key1)
# start_time = time.time()
# tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
# tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
# end_time = time.time()
# print(end_time -start_time)
# pred = contract.functions.predict_print().call()
# #     return pred

In [521]:
# print (X1, w,b,)
# b = b.tolist()
nw  = w[:,0].astype(int)
nw = nw.tolist()
print (X1, nw,b)

[[  2 117  90 ...  25  31  21]
 [  3  84  72 ...  37  26  28]
 [  6   0  68 ...  39  72  41]
 ...
 [  5 121  72 ...  26  24  30]
 [  1 126  60 ...  30  34  47]
 [  1  93  70 ...  30  31  23]] [132, 15, -25, -6, 1, 25, 4, -18] [-1168, 1000]


In [ ]:
def predict_compute()
    pred =[]
    IXWB_time=[]
    sigmoid_time=[]
    IXWB_gasuse=[]
    sigmoid_gasuse=[]
    for i in range(X1.shape[0]):
        # getting IXWB
        inputs = X1[i].tolist()
        contract = web3.eth.contract(address=cont_address,abi=abi)
        nonce = web3.eth.getTransactionCount(account2)
        tx_IXWB = contract.functions.compute_IXWB(
            inputs,nw,b
            ).buildTransaction({
            'gas': 1000000,
            'gasPrice': web3.toWei('10', 'gwei'),
            'from': account2,
            'nonce': nonce
            }) 
        signed_txn = web3.eth.account.signTransaction(tx_IXWB, private_key=private_key2)
        start_time = time.time()
        tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
        tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
        end_time = time.time()
        IXWB_time.append(end_time -start_time)
        IXWB_gasuse.append(tx_receipt.gasUsed)
        out_num,out_den = contract.functions.add_print().call()

        # getting sigmoid
        nonce= web3.eth.getTransactionCount(account2)
        tx_sigmoid = contract.functions.compute_sigmoid(
            out_num
             ).buildTransaction({
            'gas': 1000000,
            'gasPrice': web3.toWei('10', 'gwei'),
            'from': account2,
            'nonce': nonce
            }) 
        signed_txn = web3.eth.account.signTransaction(tx_sigmoid, private_key=private_key2)
        start_time = time.time()
        tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
        tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
        end_time = time.time()
        sigmoid_time.append(end_time -start_time)
        sigmoid_gasuse.append(tx_receipt.gasUsed)
        pred.append(contract.functions.predict_print().call())
        inputs.clear()

In [527]:
pred =[]
IXWB_time=[]
sigmoid_time=[]
IXWB_gasuse=[]
sigmoid_gasuse=[]

for i in range(X1.shape[0]):
    # getting IXWB
    inputs = X1[i].tolist()
#     pred.append(sigmoid_tx(account1, private_key1,inputs,weight,bias,cont_address,abi))
    contract = web3.eth.contract(address=cont_address,abi=abi)
#     print(inputs,nw,b)
    nonce = web3.eth.getTransactionCount(account2)
#     print(type(inputs),type(nw),type(b))
    tx_IXWB = contract.functions.compute_IXWB(
        inputs,nw,b
        ).buildTransaction({
        'gas': 1000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account2,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(tx_IXWB, private_key=private_key2)
    start_time = time.time()
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    end_time = time.time()
    IXWB_time.append(end_time -start_time)
    IXWB_gasuse.append(tx_receipt.gasUsed)
    out_num,out_den = contract.functions.add_print().call()

    # getting sigmoid
    nonce= web3.eth.getTransactionCount(account2)
    tx_sigmoid = contract.functions.compute_sigmoid(
        out_num
         ).buildTransaction({
        'gas': 1000000,
        'gasPrice': web3.toWei('10', 'gwei'),
        'from': account2,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(tx_sigmoid, private_key=private_key2)
    start_time = time.time()
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
    end_time = time.time()
    sigmoid_time.append(end_time -start_time)
    sigmoid_gasuse.append(tx_receipt.gasUsed)
    pred.append(contract.functions.predict_print().call())
    inputs.clear()
   

In [528]:
print(pred)

[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


In [530]:
print(accuracy_score(y1, pred))

0.7388059701492538


In [532]:
print(sigmoid_time)
print(sigmoid_gasuse)

[0.06054830551147461, 0.12253451347351074, 0.156449556350708, 0.10309863090515137, 0.12160325050354004, 0.1445465087890625, 0.10182905197143555, 0.12809371948242188, 0.12788629531860352, 0.08518171310424805, 0.08038926124572754, 0.136735200881958, 0.11088299751281738, 0.11569857597351074, 0.1114051342010498, 0.13178515434265137, 0.07615518569946289, 0.11945962905883789, 0.1148977279663086, 0.12138032913208008, 0.1106266975402832, 0.09958553314208984, 0.1390533447265625, 0.0812532901763916, 0.13999533653259277, 0.13186335563659668, 0.09899282455444336, 0.12333869934082031, 0.1005551815032959, 0.13277482986450195, 0.1580038070678711, 0.12741613388061523, 0.07145285606384277, 0.17385387420654297, 0.14792585372924805, 0.14545011520385742, 0.13996124267578125, 0.15015220642089844, 0.1551513671875, 0.12607526779174805, 0.1361687183380127, 0.11244034767150879, 0.13125228881835938, 0.10642099380493164, 0.10099005699157715, 0.12711024284362793, 0.08689236640930176, 0.11559581756591797, 0.174167