In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from keras.models import Sequential
from keras.layers import Dense
import time
import threading
import numpy as np
import json
from web3 import Web3



INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [3]:
df = pd.read_csv('diabetes.csv',sep = ',')
# starting web3 operations

ganache_url = "HTTP://127.0.0.1:8545"
# infura_url = "https://ropsten.infura.io/v3/6072fdc3b95c407caa681f63ebaf72b8"
# web3 = Web3(Web3.HTTPProvider(ganache_url))
web3 = Web3(Web3.HTTPProvider(ganache_url))
web3.isConnected()

True

In [4]:
abi = json.loads('[{ "inputs": [], "name": "add_print", "outputs": [ { "internalType": "int256", "name": "x", "type": "int256" }, { "internalType": "int256", "name": "y", "type": "int256" } ], "stateMutability": "view", "type": "function" }, { "inputs": [ { "internalType": "int256[]", "name": "input", "type": "int256[]" }, { "internalType": "int256[]", "name": "w", "type": "int256[]" }, { "internalType": "int256[]", "name": "b", "type": "int256[]" } ], "name": "compute_IXWB", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "a", "type": "int256" }, { "internalType": "int256", "name": "b", "type": "int256" }, { "internalType": "int256", "name": "c", "type": "int256" }, { "internalType": "int256", "name": "d", "type": "int256" } ], "name": "compute_addition", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "x", "type": "int256" }, { "internalType": "int256", "name": "y", "type": "int256" } ], "name": "compute_lcm", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [ { "internalType": "int256", "name": "d", "type": "int256" } ], "name": "compute_sigmoid", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "lcm_print", "outputs": [ { "internalType": "int256", "name": "", "type": "int256" } ], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "predict_print", "outputs": [ { "internalType": "int256", "name": "", "type": "int256" } ], "stateMutability": "view", "type": "function" }]')
cont_address = "0xd9145CCE52D386f254917e481eB44e9943F39138"

account1 = "0x37bfB436392DaAE0E91EdcD9c4128FBcADF3919d"
private_key1 = "e72044de2331844a3c0232dc23d43fb8ca4f555854b4da07e2fb530d003e5e2d"
account2 = "0xfbD8f1F5878b0b5b3E627e7cc14617b05B582867"
private_key2="56c8f569b23a423f9d66d46f86f7ada7ba0d28dfba03c34f661bb15358b042bb"


In [5]:
df['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']*100
df.DiabetesPedigreeFunction = df.DiabetesPedigreeFunction.astype(int)
df.BMI = df.BMI.astype(int) 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   

   DiabetesPedigreeFunction  Age  Outcome  
0                        62   50        1  
1                        35   31        0  
2                        67   32        1  
3                        16   21        0  
4                       228   33        1

In [6]:
dataset = df.to_numpy()

X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]

In [7]:
print(X[:5])
print(y[:5])

[[  6 148  72  35   0  33  62  50]
 [  1  85  66  29   0  26  35  31]
 [  8 183  64   0   0  23  67  32]
 [  1  89  66  23  94  28  16  21]
 [  0 137  40  35 168  43 228  33]]
[1 0 1 0 1]


In [8]:
# define the keras model
model = Sequential()
# model.add(Dense(12, input_dim=8, activation='sigmoid'))
# model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [9]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [10]:
4
...
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpqy1u0x6y.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpqy1u0x6y.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
50/50 [==============================] - 17s 602us/step - loss: 57.2084 - accuracy: 0.5855
Epoch 2/150
50/50 [==============================] - 0s 499us/step - loss: 38.0319 - accuracy: 0.5876
Epoch 3/150
50/50 [==============================] - 0s 519us/step - loss: 35.2118 - accuracy: 0.5614
Epoch 4/150
50/50 [==============================] - 0s 506us/step - loss: 33.4734 - accu

50/50 [==============================] - 0s 591us/step - loss: 0.6490 - accuracy: 0.6613
Epoch 73/150
50/50 [==============================] - 0s 531us/step - loss: 0.6248 - accuracy: 0.6885
Epoch 74/150
50/50 [==============================] - 0s 492us/step - loss: 0.6408 - accuracy: 0.6686
Epoch 75/150
50/50 [==============================] - 0s 499us/step - loss: 0.6109 - accuracy: 0.6890
Epoch 76/150
50/50 [==============================] - 0s 492us/step - loss: 0.5975 - accuracy: 0.6994
Epoch 77/150
50/50 [==============================] - 0s 492us/step - loss: 0.6383 - accuracy: 0.6744
Epoch 78/150
50/50 [==============================] - 0s 490us/step - loss: 0.6154 - accuracy: 0.6665
Epoch 79/150
50/50 [==============================] - 0s 490us/step - loss: 0.5889 - accuracy: 0.7088
Epoch 80/150
50/50 [==============================] - 0s 493us/step - loss: 0.6624 - accuracy: 0.6461
Epoch 81/150
50/50 [==============================] - 0s 493us/step - loss: 0.6367 - accuracy: 

In [11]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (10, 1)                   9         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None


In [12]:
4
...
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

16/16 [==============================] - 0s 582us/step - loss: 0.5898 - accuracy: 0.6880
Accuracy: 68.80


In [13]:
for layer in model.layers: 
    print(layer.get_config())
    print(layer.get_weights())
    
    w = layer.get_weights()

{'name': 'dense', 'trainable': True, 'dtype': 'float32', 'units': 1, 'activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
[array([[ 0.13188733],
       [ 0.01353893],
       [-0.02559153],
       [-0.00923569],
       [-0.0009898 ],
       [ 0.02525153],
       [ 0.00393772],
       [-0.0190467 ]], dtype=float32), array([-1.3246498], dtype=float32)]


In [14]:
weights = w[0]
bias = w[1]

In [15]:
print(X1[0])

[  2 117  90  19  71  25  31  21]


In [16]:
predictions = model.predict(X1)
# predictions

In [17]:
# for i in range(len(predictions)):
#     if(predictions[i]>=.5):
#         print(i)

In [18]:

rounded= [round(x[0]) for x in predictions]
# rounded

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, rounded)

0.7014925373134329

In [20]:
print(rounded)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


In [21]:
print(y1[:10])

[0 0 1 0 0 0 1 0 0 0]


In [22]:
w = np.zeros((8,2))
for i in range(weights.shape[0]):
    w[i][0] = int(weights[i][0]*1000)
    w[i][1] = 1000
w


array([[ 131., 1000.],
       [  13., 1000.],
       [ -25., 1000.],
       [  -9., 1000.],
       [   0., 1000.],
       [  25., 1000.],
       [   3., 1000.],
       [ -19., 1000.]])

In [23]:
b = []
b.append(int(bias*1000))
b.append(1000)

In [24]:
def compute_lcm(x, y):
   # choose the greater number
    if (x > y):
        greater = x
    else:
        greater = y
    while(True):
        if((greater % x == 0) and (greater % y == 0)):
            lcm = greater
            break
        greater += 1
    return lcm

In [25]:
def addition(a,b,c,d):
    den = compute_lcm(b,d)
#     den = b*d
    num = ((den/b)*a) + ((den/d)*c)
#     print(num,den)
    return float(num),float(den)
        

In [26]:
def IXWB(inputs,w,b):
    num=0
    den=0
    out = np.zeros((inputs.shape[0],1))
    for i in range(inputs.shape[0]):
#     for i in range(10):
#         print(inputs[i][0],w)
        for j in range(inputs.shape[1]):
            num = num + inputs[i][j]*w[j][0]
            den = w[0][1]
        num,den = addition(num,den,b[0],b[1])
        out[i][0] = num
#         out[i][1] = den
        num =0
        den =0
    return out

In [27]:
print(X1[0])
print(b[0])

[  2 117  90  19  71  25  31  21]
-1324


In [28]:
test = IXWB(X1,w,b)
# print(test)

In [29]:
# for i in range(len(test)):
#     if(test[i][0]>0):
#         print(i)

In [30]:
def sigmoidfrac(x):
    if(x>=0):
        return 1
    else:
        return 0

In [31]:
out = []
for i in range(test.shape[0]):
    out.append(sigmoidfrac(test[i][0]))
# out

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, out)

0.6940298507462687

In [33]:
print(weights)
print(bias)

[[ 0.13188733]
 [ 0.01353893]
 [-0.02559153]
 [-0.00923569]
 [-0.0009898 ]
 [ 0.02525153]
 [ 0.00393772]
 [-0.0190467 ]]
[-1.3246498]


In [34]:
# # def sigmoid_tx(acc,pk,X_input,weight,bias,cont_address,abi):
# contract = web3.eth.contract(address=cont_address,abi=abi)
# # getting IXWB
# nonce = web3.eth.getTransactionCount(account1)
# print(type(X_input),type(weight),type(bias))
# tx_IXWB = contract.functions.compute_IXWB(X_input,weight,bias
#     ).buildTransaction({
#     'gas': 100000,
#     'gasPrice': web3.toWei('1', 'gwei'),
#     'from': account1,
#     'nonce': nonce
#     }) 
# signed_txn = web3.eth.account.signTransaction(tx_IXWB, private_key=private_key1)
# start_time = time.time()
# tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
# tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
# end_time = time.time()
# print(end_time -start_time)
# out_num,out_den = contract.functions.add_print().call()

# # getting sigmoid
# nonce= web3.eth.getTransactionCount(account1)
# tx_sigmoid = contract.functions.compute_sigmoid(
#     out_num
#      ).buildTransaction({
#     'gas': 70000,
#     'gasPrice': web3.toWei('1', 'gwei'),
#     'from': account1,
#     'nonce': nonce
#     }) 
# signed_txn = web3.eth.account.signTransaction(tx_sigmoid, private_key=private_key1)
# start_time = time.time()
# tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
# tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
# end_time = time.time()
# print(end_time -start_time)
# pred = contract.functions.predict_print().call()
# #     return pred

In [35]:
# print (X1, w,b,)
# b = b.tolist()
nw  = w[:,0].astype(int)
nw = nw.tolist()
print (X1, nw,b)

[[  2 117  90 ...  25  31  21]
 [  3  84  72 ...  37  26  28]
 [  6   0  68 ...  39  72  41]
 ...
 [  5 121  72 ...  26  24  30]
 [  1 126  60 ...  30  34  47]
 [  1  93  70 ...  30  31  23]] [131, 13, -25, -9, 0, 25, 3, -19] [-1324, 1000]


In [36]:
def predict_compute(cont_address,abi,inputs, weight, bias, account, privatekey):
#     pred =[]
#     IXWB_time=[]
#     sigmoid_time=[]
#     IXWB_gasuse=[]
#     sigmoid_gasuse=[]
    print("executing IXWB")
    contract = web3.eth.contract(address=cont_address,abi=abi)
#     for i in range(X1.shape[0]):
#         # getting IXWB
    inputs = X1[i].tolist()
    nonce = web3.eth.getTransactionCount(account)
    tx_IXWB = contract.functions.compute_IXWB(
        inputs,weight,bias
        ).buildTransaction({
        'gas': 1000000,
        'gasPrice': web3.toWei('100', 'gwei'),
        'from': account,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(tx_IXWB, private_key=privatekey)
#     start_time = time.time()
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
#     end_time = time.time()
#     IXWB_time.append(end_time -start_time)
#     IXWB_gasuse.append(tx_receipt.gasUsed)
    print(tx_receipt.gasUsed)
    out_num,out_den = contract.functions.add_print().call()
    print("Executing Sigmoid")
    # getting sigmoid
    nonce= web3.eth.getTransactionCount(account1)
    tx_sigmoid = contract.functions.compute_sigmoid(
        out_num
         ).buildTransaction({
        'gas': 1000000,
        'gasPrice': web3.toWei('100', 'gwei'),
        'from': account,
        'nonce': nonce
        }) 
    signed_txn = web3.eth.account.signTransaction(tx_sigmoid, private_key=privatekey)
#     start_time = time.time()
    tx_hash = web3.eth.sendRawTransaction(signed_txn.rawTransaction)
    tx_receipt = web3.eth.waitForTransactionReceipt(tx_hash)
#     end_time = time.time()
#     sigmoid_time.append(end_time -start_time)
#     sigmoid_gasuse.append(tx_receipt.gasUsed)
    print(tx_receipt.gasUsed)
    pred.append(contract.functions.predict_print().call())
    inputs.clear()
#     return pred,IXWB_time,IXWB_gasuse,sigmoid_time,sigmoif_gasuse

In [37]:
account3 ="0x3A3faD8eF61aC63959bbB4193941205663ea69af"
private_key3 ="4d743448f76d875b4ac392da3dc504bf319267533947318698cef2d0eb6b807c"
account4 ="0xfC508F0E500410e23B65373F04d2901e718c7615"
private_key4 ="bce950eb2a43f7fcf94a5d037d254768249926d526e9734d9077c4484f64074a"
account5 ="0x49176788Ae14C48BfE31c8dff36fBb636B1FA48B"
private_key5 ="f4678fcff70debac717b0b7b6069dc96e6dbfd459a2ab9659b6d3c80d81448c9"
account6 ="0x48c5C975DAa8C1988C0f32F9e8d854eb8cAfE57d"
private_key6 ="1a17b9f46b9108cad7346e7338df7f3340d40979a8cbca1e61abd2164e9d859a"
account7 ="0x5dF6B30c276caA8D9d31Cca7FEeCEc5cA927fE71"
private_key7 ="bc550839a3b4b47e747fefe248c54501b3cbd9cfbcf5d86b8bfa5ca50750ad82"
account8 ="0x0118E72EeAf9DFD1997f7f896f942950327e299a"
private_key8 ="6130e6a5acb1a69fb4dbb73b73cfc9fd3068422867bbff1f76a35599d0c53da2"
account9 ="0xc3FC4C06648aD9215C6Cdb295625ceD1541c05E2"
private_key9 ="a26b260d2c029ed904d009a3b78f216f3fa206081f09a47dfd70427f0d37f767"
account10 ="0x1424D8455E6d98177462356B758fF919fF19Fc26"
private_key10 ="b1441ced995944f4ab2fe62743c3ba32ab14378c874c41d8e6fbd97d90f439ea"



In [38]:


if __name__ =="__main__":
    inputs = X1[0]
    weight = nw
    bias = b
    t1 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account1,private_key1))
    t2 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account2,private_key2))
    t3 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account3,private_key3))
    t4 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account4,private_key4))
    t5 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account5,private_key5))
    t6 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account6,private_key6))
    t7 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account7,private_key7))
    t8 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account8,private_key8))
    t9 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account9,private_key9))
    t10 = threading.Thread(target = predict_compute,args=(cont_address,abi,inputs,weight,bias,account10,private_key10))
    t1.start()
    t2.start()
    t3.start()
    t4.start()
    t5.start()
    t6.start()
    t7.start()
    t8.start()
    t9.start()
    t10.start()
    
    t1.join()
    t2.join()
    t3.join()
    t4.join()
    t5.join()
    t6.join()
    t7.join()
    t8.join()
    t9.join()
    t10.join()
    

executing IXWB
executing IXWB
executing IXWB
executing IXWB
executing IXWB
executing IXWB
executing IXWB
executing IXWB
executing IXWB
executing IXWB
25924
25924
25924
25924
25924
25924
25924
25924
25924
25924


Exception in thread Thread-10:
Traceback (most recent call last):
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\web3\contract.py", line 1513, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
Exception in thread Thread-8:
Traceback (most recent call last):
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\web3\contract.py", line 1513, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "c:\users\syed\appdata\local\programs

Exception in thread Thread-9:
Traceback (most recent call last):
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\web3\contract.py", line 1513, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\decoding.py", line 173, in decode
    yield decoder(stream)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\decoding.py", line 127, in __cal

    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
Exception in thread Thread-11:
Traceback (most recent call last):
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\web3\contract.py", line 1513, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "c:\users\syed\appdata\local\programs\python\python39\lib\site-packages\eth_ab

In [39]:
print(pred)

NameError: name 'pred' is not defined

In [ ]:
print(accuracy_score(y1, pred))

In [ ]:
print(sigmoid_time)
print(sigmoid_gasuse)