In [2]:
#Independent variables
import random
import numpy as np
import pandas as pd
from numpy import loadtxt
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score


In [3]:
dataset = loadtxt('pima-diabetes.txt', delimiter=',')
X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]
type(X)

numpy.ndarray

In [4]:
#Define Hyperparameters
np.random.seed(42)
weights = np.random.rand(8,1)
bias = np.random.rand(1)
lr = .0001 #learning rate
weights

array([[0.37454012],
       [0.95071431],
       [0.73199394],
       [0.59865848],
       [0.15601864],
       [0.15599452],
       [0.05808361],
       [0.86617615]])

In [5]:
weights=weights.reshape(8,1)

In [6]:
weights

array([[0.37454012],
       [0.95071431],
       [0.73199394],
       [0.59865848],
       [0.15601864],
       [0.15599452],
       [0.05808361],
       [0.86617615]])

In [7]:
bias

array([0.60111501])

In [8]:
labels = np.reshape(y, (500,1))

In [9]:
#define activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [10]:
#define derivative
def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [11]:
inputs = X  # set aside the original input
 # dot product of input and add bias
XW = np.dot(inputs, weights)+ bias 
print(XW)


[[265.79732543]
 [178.48036948]
 [255.81710749]
 [184.91857094]
 [242.73298315]
 [196.91464574]
 [172.73767487]
 [144.31215944]
 [402.2125889 ]
 [239.49512995]
 [205.88306415]
 [253.643043  ]
 [248.73851043]
 [426.16415544]
 [299.9074647 ]
 [130.71991123]
 [272.32214396]
 [190.60052988]
 [191.90662134]
 [227.6306936 ]
 [276.69781466]
 [208.05919316]
 [297.19035426]
 [226.27776614]
 [301.91422027]
 [248.30920337]
 [242.01612432]
 [195.03226473]
 [284.73312501]
 [219.30451296]
 [234.18442636]
 [296.57719578]
 [165.7935405 ]
 [185.02565732]
 [239.30071618]
 [226.03758457]
 [227.07074848]
 [223.74168685]
 [191.20868988]
 [275.13893173]
 [273.42882387]
 [229.51531301]
 [227.24908794]
 [352.77327478]
 [240.17245511]
 [271.70509699]
 [210.55650925]
 [159.71202478]
 [201.58596808]
 [123.85384102]
 [198.94820383]
 [174.52024465]
 [180.41994689]
 [359.48494609]
 [314.47778534]
 [134.7560592 ]
 [342.96837539]
 [247.37745254]
 [243.96188238]
 [219.51307052]
 [ 99.41755347]
 [221.67477451]
 [124.80

In [12]:
z = sigmoid(XW)  #sigmoid activation function
print(z)
error = z - labels  #backprop step1
print(error)
dcost = error


[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.

In [13]:
dpred = sigmoid_derivative(z)
print(dpred)


[[0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19

In [14]:
z_del = dcost * dpred
inputs = X.T
print(z_del)
# print(inputs)


[[0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.        ]
 [0.19661193]
 [0.19661193]
 [0.19661193]
 [0.        ]
 [0.19

In [15]:
print(lr*np.dot(inputs,z_del))

[[0.02032967]
 [0.69091399]
 [0.4263923 ]
 [0.12478959]
 [0.42597941]
 [0.18797674]
 [0.00274893]
 [0.19558955]]


In [1]:
# print(inputs[6][:])

In [25]:
print(z_del[:][0])

[-0.25]


In [16]:
weights = weights - lr*np.dot(inputs, z_del)

for num in z_del:
    bias = bias - lr*num
z_del

array([[0.        ],
       [0.19661193],
       [0.        ],
       [0.19661193],
       [0.        ],
       [0.19661193],
       [0.        ],
       [0.19661193],
       [0.        ],
       [0.        ],
       [0.19661193],
       [0.        ],
       [0.19661193],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.19661193],
       [0.        ],
       [0.19661193],
       [0.19661193],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.19661193],
       [0.19661193],
       [0.19661193],
       [0.19661193],
       [0.        ],
       [0.19661193],
       [0.19661193],
       [0.19661193],
       [0.19661193],
       [0.19661193],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.19661193],
       [0.19661193],
       [0.19661193],
       [0.        ],
       [0.19661193],
       [0.        ],
       [0.19661193],
       [0.196

In [17]:
weights

array([[ 0.35421044],
       [ 0.25980031],
       [ 0.30560164],
       [ 0.47386889],
       [-0.26996077],
       [-0.03198222],
       [ 0.05533468],
       [ 0.67058659]])

In [18]:

#train ANN model
for epoch in range(10000):
    inputs = X  # set aside the original input
    XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
    z = sigmoid(XW)  #sigmoid activation function
    error = z - labels  #backprop step1
    
    dcost = error
    dpred = sigmoid_derivative(z)

    z_del = dcost * dpred
    inputs = X.T
    
    weights = weights - lr*np.dot(inputs, z_del)
    
    for num in z_del:
        bias = bias - lr*num

In [19]:
print(weights)
print(bias)

[[ 8.38165288]
 [ 0.95773855]
 [-1.02984431]
 [-0.3876732 ]
 [ 0.49267081]
 [-0.05587854]
 [ 0.89587093]
 [-1.20504023]]
[-3.51514082]


# Predict Points

In [20]:
pred = sigmoid(np.dot(X1, weights) + bias)
pred = pred.astype(int)

In [21]:
pred

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
    

In [22]:
accuracy_score(y1, pred)*100

55.970149253731336