In [689]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from keras.models import Sequential
from keras.layers import Dense
df = pd.read_csv('diabetes.csv',sep = ',')
len(df)

768

In [690]:
df['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']*100
df.DiabetesPedigreeFunction = df.DiabetesPedigreeFunction.astype(int)
df.BMI = df.BMI.astype(int) 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   

   DiabetesPedigreeFunction  Age  Outcome  
0                        62   50        1  
1                        35   31        0  
2                        67   32        1  
3                        16   21        0  
4                       228   33        1

In [691]:
dataset = df.to_numpy()

X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]

In [692]:
print(X[:5])
print(y[:5])

[[  6 148  72  35   0  33  62  50]
 [  1  85  66  29   0  26  35  31]
 [  8 183  64   0   0  23  67  32]
 [  1  89  66  23  94  28  16  21]
 [  0 137  40  35 168  43 228  33]]
[1 0 1 0 1]


In [693]:
# define the keras model
model = Sequential()
# model.add(Dense(12, input_dim=8, activation='sigmoid'))
# model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [694]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [695]:
4
...
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
50/50 [==============================] - 1s 535us/step - loss: 16.1297 - accuracy: 0.6163
Epoch 2/150
50/50 [==============================] - 0s 506us/step - loss: 18.4375 - accuracy: 0.5385
Epoch 3/150
50/50 [==============================] - 0s 469us/step - loss: 13.6766 - accuracy: 0.5610
Epoch 4/150
50/50 [==============================] - 0s 489us/step - loss: 13.0671 - accuracy: 0.5775
Epoch 5/150
50/50 [==============================] - 0s 510us/step - loss: 13.0471 - accuracy: 0.5739
Epoch 6/150
50/50 [==============================] - 0s 490us/step - loss: 10.7761 - accuracy: 0.6076
Epoch 7/150
50/50 [==============================] - 0s 490us/step - loss: 11.0049 - accuracy: 0.6117
Epoch 8/150
50/50 [==============================] - 0s 487us/step - loss: 9.6265 - accuracy: 0.5908
Epoch 9/150
50/50 [==============================] - 0s 510us/step - loss: 8.7827 - accuracy: 0.5965
Epoch 10/150
50/50 [==============================] - 0s 503us/step - loss: 8.1379 -

50/50 [==============================] - 0s 501us/step - loss: 0.6690 - accuracy: 0.6373
Epoch 82/150
50/50 [==============================] - 0s 510us/step - loss: 0.6375 - accuracy: 0.6713
Epoch 83/150
50/50 [==============================] - 0s 530us/step - loss: 0.6538 - accuracy: 0.6513
Epoch 84/150
50/50 [==============================] - 0s 510us/step - loss: 0.6565 - accuracy: 0.6348
Epoch 85/150
50/50 [==============================] - 0s 510us/step - loss: 0.6693 - accuracy: 0.6475
Epoch 86/150
50/50 [==============================] - 0s 510us/step - loss: 0.6217 - accuracy: 0.6470
Epoch 87/150
50/50 [==============================] - 0s 508us/step - loss: 0.6074 - accuracy: 0.6839
Epoch 88/150
50/50 [==============================] - 0s 504us/step - loss: 0.6411 - accuracy: 0.6474
Epoch 89/150
50/50 [==============================] - 0s 510us/step - loss: 0.6507 - accuracy: 0.6418
Epoch 90/150
50/50 [==============================] - 0s 518us/step - loss: 0.6128 - accuracy: 

In [696]:
print(model.summary())

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_26 (Dense)             (10, 1)                   9         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None


In [697]:
4
...
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

16/16 [==============================] - 0s 534us/step - loss: 0.5879 - accuracy: 0.7160
Accuracy: 71.60


In [698]:
for layer in model.layers: 
    print(layer.get_config())
    print(layer.get_weights())
    
    w = layer.get_weights()

{'name': 'dense_26', 'trainable': True, 'dtype': 'float32', 'units': 1, 'activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
[array([[ 0.13203669],
       [ 0.01406144],
       [-0.02519551],
       [-0.00595888],
       [ 0.00296422],
       [ 0.02580162],
       [ 0.00380746],
       [-0.01828524]], dtype=float32), array([-1.1897464], dtype=float32)]


In [699]:
weights = w[0]
bias = w[1]

In [700]:
print(X1[0])

[  2 117  90  19  71  25  31  21]


In [701]:
predictions = model.predict(X1)
predictions

array([[0.25506896],
       [0.25434548],
       [0.1389032 ],
       [0.4771852 ],
       [0.20906636],
       [0.34860092],
       [0.39950514],
       [0.5564039 ],
       [0.45996436],
       [0.3134054 ],
       [0.40001443],
       [0.49591318],
       [0.3099665 ],
       [0.32830822],
       [0.41166165],
       [0.58067226],
       [0.5510434 ],
       [0.36858624],
       [0.55679405],
       [0.42247438],
       [0.18667176],
       [0.4045139 ],
       [0.6896741 ],
       [0.59019935],
       [0.48021555],
       [0.2965233 ],
       [0.27178997],
       [0.36934075],
       [0.43129376],
       [0.2762888 ],
       [0.5253137 ],
       [0.35003254],
       [0.31985378],
       [0.77796435],
       [0.37515676],
       [0.8473319 ],
       [0.11905357],
       [0.09068435],
       [0.44900745],
       [0.39628193],
       [0.5691699 ],
       [0.53592163],
       [0.31633657],
       [0.24734026],
       [0.21405882],
       [0.73757106],
       [0.7631978 ],
       [0.558

In [702]:
for i in range(len(predictions)):
    if(predictions[i]>=.5):
        print(i)

7
15
16
18
22
23
30
33
35
40
41
45
46
47
55
58
61
68
74
76
78
84
86
88
89
90
93
94
95
97
99
101
103
104
106
108
110
111
112
114
119
122
130
134
135
138
143
145
147
148
155
160
161
162
163
168
169
170
173
175
178
179
185
191
192
193
195
196
197
199
203
206
207
208
210
212
213
215
216
232
238
240
241
244
248
249
250
253
254
261


In [703]:

rounded= [round(x[0]) for x in predictions]
rounded

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,


In [704]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, rounded)

0.7089552238805971

In [705]:
print(rounded)

[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


In [706]:
print(y1[:10])

[0 0 1 0 0 0 1 0 0 0]


In [707]:
w = np.zeros((8,2))
for i in range(weights.shape[0]):
    w[i][0] = int(weights[i][0]*1000)
    w[i][1] = 1000
w


array([[ 132., 1000.],
       [  14., 1000.],
       [ -25., 1000.],
       [  -5., 1000.],
       [   2., 1000.],
       [  25., 1000.],
       [   3., 1000.],
       [ -18., 1000.]])

In [708]:
b = np.zeros((2,1))
b[0][0] = int(bias*1000)
b [1][0]= 1000

In [709]:
def compute_lcm(x, y):
   # choose the greater number
    if (x > y):
        greater = x
    else:
        greater = y
    while(True):
        if((greater % x == 0) and (greater % y == 0)):
            lcm = greater
            break
        greater += 1
    return lcm

In [710]:
def addition(a,b,c,d):
    den = compute_lcm(b,d)
#     den = b*d
    num = ((den/b)*a) + ((den/d)*c)
#     print(num,den)
    return float(num),float(den)
        

In [711]:
def IXWB(inputs,w,b):
    num=0
    den=0
    out = np.zeros((inputs.shape[0],1))
    for i in range(inputs.shape[0]):
#     for i in range(10):
#         print(inputs[i][0],w)
        for j in range(inputs.shape[1]):
            num = num + inputs[i][j]*w[j][0]
            den = w[0][1]
        num,den = addition(num,den,b[0][0],b[1][0])
        out[i][0] = num
#         out[i][1] = den
        num =0
        den =0
    return out

In [712]:
print(X1[0])
print(w)

[  2 117  90  19  71  25  31  21]
[[ 132. 1000.]
 [  14. 1000.]
 [ -25. 1000.]
 [  -5. 1000.]
 [   2. 1000.]
 [  25. 1000.]
 [   3. 1000.]
 [ -18. 1000.]]


In [713]:
test = IXWB(X1,w,b)
print(test)



[[-1150.]
 [-1078.]
 [-1849.]
 [ -210.]
 [-1320.]
 [ -650.]
 [ -506.]
 [   17.]
 [ -302.]
 [ -810.]
 [ -400.]
 [ -226.]
 [ -811.]
 [ -766.]
 [ -442.]
 [  208.]
 [   16.]
 [ -568.]
 [  207.]
 [ -655.]
 [-1522.]
 [ -515.]
 [  785.]
 [  304.]
 [ -105.]
 [ -886.]
 [-1071.]
 [ -636.]
 [ -479.]
 [-1020.]
 [  -53.]
 [ -694.]
 [ -857.]
 [ 1194.]
 [ -649.]
 [ 1663.]
 [-2015.]
 [-2353.]
 [ -450.]
 [ -610.]
 [   46.]
 [  -70.]
 [ -806.]
 [-1168.]
 [-1382.]
 [  806.]
 [  898.]
 [   69.]
 [ -890.]
 [ -682.]
 [ -966.]
 [ -753.]
 [-1442.]
 [ -970.]
 [ -829.]
 [   -7.]
 [-1176.]
 [ -793.]
 [  235.]
 [ -187.]
 [ -658.]
 [  992.]
 [ -942.]
 [ -277.]
 [-1421.]
 [ -363.]
 [ -890.]
 [ -571.]
 [   10.]
 [ -649.]
 [-1272.]
 [-1255.]
 [ -298.]
 [ -387.]
 [  -92.]
 [  -91.]
 [  388.]
 [ -394.]
 [  392.]
 [ -507.]
 [ -772.]
 [ -307.]
 [ -337.]
 [ -382.]
 [  751.]
 [ -933.]
 [  367.]
 [ -455.]
 [  -68.]
 [   10.]
 [  133.]
 [ -683.]
 [ -767.]
 [ -200.]
 [  192.]
 [  301.]
 [-1797.]
 [    6.]
 [ -245.]
 [ -104.]


In [714]:
# for i in range(len(test)):
#     if(test[i][0]>0):
#         print(i)

In [715]:
def sigmoidfrac(x):
    if(x>=0):
        return 1
    else:
        return 0

In [716]:
for i in range(test.shape[0]):
    out[i] = sigmoidfrac(test[i][0])
out

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],

In [717]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, out)

0.7425373134328358

In [718]:
print(final)

[[1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.