In [36]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from keras.models import Sequential
from keras.layers import Dense
df = pd.read_csv('diabetes.csv',sep = ',')
len(df)

768

In [37]:
# df['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']*100
df.DiabetesPedigreeFunction = df.DiabetesPedigreeFunction.astype(int)
df.BMI = df.BMI.astype(int) 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   

   DiabetesPedigreeFunction  Age  Outcome  
0                         0   50        1  
1                         0   31        0  
2                         0   32        1  
3                         0   21        0  
4                         2   33        1

In [38]:
dataset = df.to_numpy()

X = dataset[:500,0:8]
X1 = dataset[500:,0:8]
y = dataset[:500,8]
y1 = dataset[500:,8]

In [39]:
print(X[:5])
print(y[:5])

[[  6 148  72  35   0  33   0  50]
 [  1  85  66  29   0  26   0  31]
 [  8 183  64   0   0  23   0  32]
 [  1  89  66  23  94  28   0  21]
 [  0 137  40  35 168  43   2  33]]
[1 0 1 0 1]


In [40]:
# define the keras model
model = Sequential()
# model.add(Dense(12, input_dim=8, activation='sigmoid'))
# model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [41]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [42]:
4
...
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
50/50 [==============================] - 1s 675us/step - loss: 65.3747 - accuracy: 0.3815
Epoch 2/150
50/50 [==============================] - 0s 547us/step - loss: 58.1262 - accuracy: 0.3580
Epoch 3/150
50/50 [==============================] - 0s 530us/step - loss: 45.7899 - accuracy: 0.3824
Epoch 4/150
50/50 [==============================] - 0s 757us/step - loss: 35.6195 - accuracy: 0.3934
Epoch 5/150
50/50 [==============================] - 0s 530us/step - loss: 28.2046 - accuracy: 0.3349
Epoch 6/150
50/50 [==============================] - 0s 539us/step - loss: 17.9772 - accuracy: 0.3664
Epoch 7/150
50/50 [==============================] - 0s 532us/step - loss: 9.7216 - accuracy: 0.3765
Epoch 8/150
50/50 [==============================] - 0s 571us/step - loss: 6.9945 - accuracy: 0.3224
Epoch 9/150
50/50 [==============================] - 0s 530us/step - loss: 5.1163 - accuracy: 0.3633
Epoch 10/150
50/50 [==============================] - 0s 510us/step - loss: 4.5744 - 

50/50 [==============================] - 0s 530us/step - loss: 0.6192 - accuracy: 0.6978
Epoch 82/150
50/50 [==============================] - 0s 530us/step - loss: 0.6026 - accuracy: 0.7053
Epoch 83/150
50/50 [==============================] - 0s 530us/step - loss: 0.6079 - accuracy: 0.6972
Epoch 84/150
50/50 [==============================] - 0s 510us/step - loss: 0.5859 - accuracy: 0.7042
Epoch 85/150
50/50 [==============================] - 0s 545us/step - loss: 0.5944 - accuracy: 0.7022
Epoch 86/150
50/50 [==============================] - 0s 659us/step - loss: 0.5956 - accuracy: 0.7038
Epoch 87/150
50/50 [==============================] - 0s 551us/step - loss: 0.5993 - accuracy: 0.6944
Epoch 88/150
50/50 [==============================] - 0s 511us/step - loss: 0.6254 - accuracy: 0.6915
Epoch 89/150
50/50 [==============================] - 0s 551us/step - loss: 0.6226 - accuracy: 0.6876
Epoch 90/150
50/50 [==============================] - 0s 510us/step - loss: 0.6067 - accuracy: 

In [43]:
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (10, 1)                   9         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None


In [44]:
4
...
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

16/16 [==============================] - 0s 533us/step - loss: 0.5670 - accuracy: 0.7260
Accuracy: 72.60


In [45]:
for layer in model.layers: 
    print(layer.get_config())
    print(layer.get_weights())
    
    w = layer.get_weights()

{'name': 'dense_3', 'trainable': True, 'dtype': 'float32', 'units': 1, 'activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
[array([[ 1.2862502e-01],
       [ 1.4540717e-02],
       [-2.4758341e-02],
       [-7.2858818e-03],
       [-3.6972335e-05],
       [ 2.9892247e-02],
       [ 6.8439019e-01],
       [-1.6458422e-02]], dtype=float32), array([-1.3415163], dtype=float32)]


In [46]:
weights = w[0]
bias = w[1]

In [47]:
predictions = model.predict(X1)
predictions

array([[0.20576727],
       [0.24884304],
       [0.1129404 ],
       [0.3699884 ],
       [0.20959702],
       [0.34663305],
       [0.34408963],
       [0.37975153],
       [0.32739136],
       [0.30899686],
       [0.38336945],
       [0.33737922],
       [0.3140123 ],
       [0.29920793],
       [0.34471148],
       [0.5030519 ],
       [0.3814094 ],
       [0.38080442],
       [0.55773133],
       [0.19704425],
       [0.15080205],
       [0.30576903],
       [0.6592506 ],
       [0.5619366 ],
       [0.48940712],
       [0.26402843],
       [0.20816773],
       [0.3032204 ],
       [0.27439564],
       [0.24423754],
       [0.39506418],
       [0.32802206],
       [0.22628272],
       [0.7521484 ],
       [0.39543146],
       [0.8416247 ],
       [0.12639636],
       [0.07776034],
       [0.25821304],
       [0.23668441],
       [0.37008303],
       [0.36493057],
       [0.2710022 ],
       [0.22284642],
       [0.16807929],
       [0.57636195],
       [0.7373379 ],
       [0.440

In [48]:

rounded= [round(x[0]) for x in predictions]
rounded

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,


In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, rounded)

0.7276119402985075

In [50]:
print(rounded)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


In [51]:
print(y1[:10])

[0 0 1 0 0 0 1 0 0 0]


In [52]:
for i in range(weights.shape[0]):
    weights[i][0] = int(weights[i][0]*1000)
weights


array([[128.],
       [ 14.],
       [-24.],
       [ -7.],
       [  0.],
       [ 29.],
       [684.],
       [-16.]], dtype=float32)

In [53]:
b = int(bias*100)

In [54]:
def sigmoidfrac(x):
    if(x<=5):
        return 1
    else:
        return 0

In [55]:
final = np.zeros((len(X1),1))
for i in range(len(X1)):
    num=0
    den=0
    a = X1[i]
    for j in range(len(a)):
        num = num + a[j]*weights[j][0] 
    x = int(num+bias)
#     print(x)
    pred  = sigmoidfrac(x)
    final[i] = pred

-11
231
-677
800
14
709
660
821
603
531
870
639
560
471
680
1309
852
837
1558
-45
-372
508
1946
1556
1255
307
1
495
353
192
885
593
107
2385
907
2918
-586
-1106
273
169
809
767
364
96
-252
1615
2326
1074
281
519
321
215
-22
175
201
852
146
593
1598
1130
785
1703
163
821
-151
592
340
534
1042
356
98
72
816
701
356
1022
1218
868
1715
633
512
956
999
1028
746
293
1770
856
1402
1229
1278
347
592
1096
858
1140
-318
1110
1208
865
-207
2329
137
1070
3308
877
1986
-97
642
429
909
1624
1302
632
1624
431
432
-160
1278
2208
118
510
2196
356
764
-61
476
566
776
472
1193
-123
754
262
1307
1681
362
151
852
-230
-347
1224
945
2086
237
1082
708
1773
1189
267
286
688
842
960
368
1689
288
680
955
555
1449
2337
879
1371
980
61
254
1106
813
1374
1435
439
-211
760
255
2190
1118
475
1472
485
-157
1195
443
836
-529
659
981
639
456
450
752
1652
807
1139
341
736
1184
1757
637
1342
548
426
346
2506
466
397
2408
1415
1782
530
1482
542
1925
760
363
2494
1120
511
507
166
-227
652
546
461
-367
449
319
350
878
812
4

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y1, final)

0.5932835820895522

In [57]:
print(final)

[[1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.