In [1]:
import numpy as np
a=np.random.randn(3,3)

b=np.random.randn(3,1)

c = a*b

In [2]:
print(c)

[[ 0.80339414 -0.6258041   0.01580566]
 [-0.02853965  0.04055798  0.06864494]
 [ 0.53384107  0.13603618 -0.32073779]]


In [11]:
a=np.random.randn(4,3)
b=np.random.randn(4,1)

In [12]:
c = np.zeros((4,4))
for i in range(3):
    for j in range(4):
        c[i][j] = a[j][i] + b[j]

In [13]:
c

array([[-1.83585031, -2.85137521,  0.81443873,  0.96257434],
       [ 0.18276876, -3.42193046, -0.24600764,  0.12958639],
       [-1.26235865, -0.32244609,  1.40873991,  0.78985729],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [17]:


c = a.T + b.T
c

array([[-1.83585031, -2.85137521,  0.81443873,  0.96257434],
       [ 0.18276876, -3.42193046, -0.24600764,  0.12958639],
       [-1.26235865, -0.32244609,  1.40873991,  0.78985729]])